background = "#24273a"
foreground = "#cad3f5"
muted = "#6e738d"
accent = "#c6a0f6"
selection = "#494d64"
error = "#ed8796"
warning = "#eed49f"
info = "#8aadf4"
hint = "#8bd5ca"
mode = "dark"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#c6a0f6"
cyan = "#8bd5ca"
bright_red = "#ed8796"
bright_green = "#a6da95"
bright_yellow = "#eed49f"
bright_blue = "#8aadf4"
bright_magenta = "#c6a0f6"
bright_cyan = "#8bd5ca"
bright_foreground = "#cad3f5"
dark_foreground = "#6e738d"
light_foreground = "#cad3f5"
dark_background = "#24273a"
darker_background = "#24273a"
lighter_background = "#494d64"
orange = "#f5a97f"
brown = "#6e738d"
