mode = "dark"
accent = "#7b77b9"
background = "#0b031f"
blue = "#7b77b9"
bright_blue = "#8e8adc"
bright_cyan = "#beecff"
bright_foreground = "#f5f4ff"
bright_green = "#94deff"
bright_magenta = "#d2aaff"
bright_red = "#c795da"
bright_yellow = "#ffc6ff"
brown = "#605f66"
color0 = "#0b031f"
color1 = "#ac85bb"
color10 = "#94deff"
color11 = "#ffc6ff"
color12 = "#8e8adc"
color13 = "#d2aaff"
color14 = "#beecff"
color15 = "#f5f4ff"
color2 = "#8fc7ff"
color3 = "#ffd0ff"
color4 = "#7b77b9"
color5 = "#b99aec"
color6 = "#b1d7ff"
color7 = "#f8dfff"
color8 = "#605f66"
color9 = "#c795da"
cursor = "#f8dfff"
cyan = "#b1d7ff"
dark_background = "#0b031f"
dark_foreground = "#f8dfff"
darker_background = "#0b031f"
error = "#ac85bb"
foreground = "#f8dfff"
green = "#8fc7ff"
hint = "#b1d7ff"
info = "#7b77b9"
light_foreground = "#f8dfff"
lighter_background = "#0b031f"
magenta = "#b99aec"
muted = "#605f66"
orange = "#ffd0ff"
red = "#ac85bb"
selection = "#605f66"
selection_background = "#605f66"
selection_foreground = "#f8dfff"
warning = "#ffd0ff"
yellow = "#ffd0ff"
