#!/bin/bash

export REPOS="$HOME/repos"
export DOTS="$REPOS/dots"
export DOTFILES=${DOTFILES:="$HOME/.dots"}
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

ORANGE="\033[38;5;216m"
PURPLE="\033[38;5;140m"
GRAY="\033[0;30m"
WHITE="\033[0;37m"
RED="\033[0;31m"
GREEN="\033[0;32m"
BLUE="\033[0;34m"
YELLOW="\033[0;33m"
CYAN="\033[0;36m"
PINK="\033[0;35m"
GRAYB="\033[1;30m"
WHITEB="\033[1;37m"
REDB="\033[1;31m"
BLUEB="\033[1;34m"
GREENB="\033[1;32m"
YELLOWB="\033[1;33m"
CYANB="\033[1;36m"
PINKB="\033[1;35m"

NC="\033[0m"

HEADER="${GREENB}"
LINECOLOR="${GRAYB}"
PANELBG="\033[48;5;233m"
menu_symbol="󰅂"
solsymble="" 

cecho(){
    printf "${(P)1}${2} ${NC}\n"
}

logo() {
	topdoubleline
	echo -e "${LINECOLOR}\033[48;5;234m║${HEADER}                                        ${LINECOLOR}║${NC}"
	echo -e "${LINECOLOR}\033[48;5;233m║${HEADER}    ░░░░░░   ░░░░░░  ░░░░░░░ ░░░░░░░    ${LINECOLOR}║${NC}"
	echo -e "${LINECOLOR}\033[48;5;233m║${HEADER}    ▒▒   ▒▒ ▒▒    ▒▒      ▒▒ ▒▒         ${LINECOLOR}║${NC}"
	echo -e "${LINECOLOR}\033[48;5;232m║${HEADER}    ▒▒   ▒▒ ▒▒    ▒▒    ▒▒   ▒▒▒▒▒▒▒    ${LINECOLOR}║${NC}"
	echo -e "${LINECOLOR}\033[48;5;232m║${HEADER}    ▓▓   ▓▓ ▓▓    ▓▓   ▓▓         ▓▓    ${LINECOLOR}║${NC}"
	echo -e "${LINECOLOR}\033[48;5;016m║${HEADER}    ██████   ██████    ██    ███████    ${LINECOLOR}║${NC}"
	echo -e "${LINECOLOR}\033[48;5;016m║${HEADER}                                        ${LINECOLOR}║${NC}"
   bottomdoubleline
}

menu() {
	menutitle		"OPTIONS                              "
	linelinebreak
	menuopt			"setup                              "
	menuopt			"link                               "
	menuopt			"update                             "
	linelinebreak
	bottomline
}

setup_start() {
	title "Installing packages.                 "
	linebreak
	sudo apt -qq update -y
	sudo apt -qq upgrade -y	
	installnala
	installpkgs
	installrustup
	installstarship
	installbob
	installthorium
	link_bin batcat bat
	link_bin fdfind fd
	xdg-user-dirs-update
	createdir "$REPOS"
	createdir "$DOTFILES"
	createdir "$HOME/.local/bin"
    createdir "$HOME/bin"
	createdir "$XDG_CONFIG_HOME"
	createdir "$XDG_CACHE_HOME"
	createdir "$XDG_DATA_HOME"
	createdir "$XDG_STATE_HOME"
	linebreak
}

setup_link() {
	title "Creating symlinks.                   "
	linebreak
	take "5nik7/dots" "$DOTS"
	take "5nik7/starship" "$REPOS/starship"
    take "5nik7/neoviim" "$REPOS/neoviim"
	symlink "$DOTS/dots" "$DOTFILES/dots"
	symlink "$DOTS/zsh" "$DOTFILES/zsh"
	symlink "$DOTS/git" "$DOTFILES/git"
	symlink "$DOTS/kitty" "$DOTFILES/kitty"
	symlink "$DOTS/ranger" "$DOTFILES/ranger"
	symlink "$DOTS/btop" "$DOTFILES/btop"
	symlink "$DOTS/bottom" "$DOTFILES/bottom"
	symlink "$DOTS/bat" "$DOTFILES/bat"
	symlink "$DOTS/fsh" "$DOTFILES/fsh"
	symlink "$DOTS/lsd" "$DOTFILES/lsd"
	symlink "$REPOS/starship" "$DOTFILES/starship"
	symlink "$REPOS/neoviim" "$DOTFILES/nvim"
	symlink "$DOTS/git/gitconfig" "$HOME/.gitconfig"
	symlink "$DOTS/zsh/zshrc" "$HOME/.zshrc"
	symlink "$DOTS/bat" "$XDG_CONFIG_HOME/bat"
	symlink "$DOTS/kitty" "$XDG_CONFIG_HOME/kitty"
	symlink "$DOTS/btop" "$XDG_CONFIG_HOME/btop"
	symlink "$DOTS/bottom" "$XDG_CONFIG_HOME/bottom"
	symlink "$DOTS/fsh" "$XDG_CONFIG_HOME/fsh"
	symlink "$DOTS/ranger" "$XDG_CONFIG_HOME/ranger"
	symlink "$REPOS/starship/starship.toml" "$XDG_CONFIG_HOME/starship.toml"
	symlink "$REPOS/neoviim" "$XDG_CONFIG_HOME/nvim"
	linebreak
}

setup_zsh() {
	if [[ ! $SHELL = "/usr/bin/zsh" ]]; then
		title "Setting up ZSH.                      "
		sudo apt -qq install zsh -y
		setshell
	fi
}
menutitle() {
	topline
	echo -e "${LINECOLOR}${PANELBG}║  ${BLUEB}$1 ${LINECOLOR}║${NC}"
	middleline
}

title() {
	topline
	echo -e "${LINECOLOR}${PANELBG}║  ${BLUEB}$1 ${LINECOLOR}║${NC}"
	bottomline
}

menuopt() {
	echo -e "${LINECOLOR}${PANELBG}║  ${GRAY}${PANELBG}${menu_symbol} ${PINKB}$1 ${LINECOLOR}║${NC}"
}

topline() {
	echo -e "${LINECOLOR}${PANELBG}╔════════════════════════════════════════╗${NC}"
}


middleline() {
	echo -e "${LINECOLOR}${PANELBG}╠════════════════════════════════════════╣${NC}"
}

bottomline() {
	echo -e "${LINECOLOR}${PANELBG}╚════════════════════════════════════════╝${NC}"
}

topdoubleline() {
	echo -e "${LINECOLOR}\033[48;5;234m╔════════════════════════════════════════╗${NC}"
}

middledoubleline() {
	echo -e "${LINECOLOR}${PANELBG}╠════════════════════════════════════════╣${NC}"
}

bottomdoubleline() {
	echo -e "${LINECOLOR}\033[48;5;016m╚════════════════════════════════════════╝${NC}"
}

texture() {
	echo -e "${LINECOLOR}${solsymble}󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌${NC}"
}

linebreak() {
	echo -e ""
}

linelinebreak() {
	echo -e "${LINECOLOR}${PANELBG}║                                        ║${NC}"
}

success() {
	topline
	echo -e "${LINECOLOR}${PANELBG}║   ${GREENB}$1                                ${LINECOLOR}║${NC}"
	bottomline
}

print_default() {
	echo -e "$*"
}

print_info() {
	echo -e "\e[1;36m$*\e[m" # cyan
}

print_notice() {
	echo -e "\e[1;35m$*\e[m" # magenta
}

print_success() {
	echo -e "\e[1;32m$*\e[m" # green
}

print_warning() {
	echo -e "\e[1;33m$*\e[m" # yellow
}

print_error() {
	echo -e "\e[1;31m$*\e[m" # red
}

print_debug() {
	echo -e "\e[1;34m$*\e[m" # blue
}

error() {
	echo -e "    ${COLOR_RED} ${NC}$1"
}

warning() {
	echo -e "    ${COLOR_YELLOW} ${NC}$1"
}

info() {
	echo -e "    ${BLUE} ${NC}$1"
}

ask(){
	while true; do
		read -rp " Start the setup? [Y/n]: " yn
			case $yn in
				[Yy]* ) break;;
				[Nn]* ) exit;;
				* ) break;;
			esac
  		done
	clear
}

fold1() {
    cecho "BLUE" $(basename "$1")
}

fold2() {
    echo -e $(basename "$(dirname "$1")")/$(basename "$1")
}

fold3() {
    echo -e $(basename "$(dirname "$(dirname "$1")")")/$(basename "$(dirname "$1")")/$(basename "$1")
}

createdir() {
	if [ ! -d "$1" ]; then
		mkdir -p "$1"
		echo -e "${LINECOLOR}${solsymble}${NC} ${BLUE}Created${NC} ${CYANB}$1${NC}"
	fi
}

take() {
	if [ ! -d "$2" ]; then
		git clone "https://github.com/$1.git" "$2"
		echo -e "${LINECOLOR}${solsymble}${NC} ${PURPLE}Github.com/${NC}${PINKB}$1 ${GRAY}->${NC} ${CYANB}$2${NC}"
	fi
}

link_bin() {
	if [ ! -e "$HOME/.local/bin/$2" ]; then
			ln -s $(which $1) $HOME/.local/bin/$2
	fi
}

symlink() {
	if [ ! -e "$2" ]; then
		ln -s "$1" "$2"
		echo -e "${LINECOLOR}${solsymble}${NC}  ${BLUE}$1${NC} ${GRAY}->${NC} ${CYANB}$2${NC}"
	else
		echo -e "${LINECOLOR}${solsymble}${NC}  ${GRAYB}$2${NC} ${GRAY}already exists${NC}"
	fi
}

backup() {
	if [ -f "$1" ]; then
		mv -f "$1" "${1}.bak"
		echo -e "${LINECOLOR}${solsymble}${NC}  ${ORANGE}$1${NC} ${GRAY}->${NC} ${YELLOWB}$1.bak${NC}"
	else
		echo -e "${LINECOLOR}${solsymble}${NC}  ${PINKB}$1${NC} ${PINK}does not exist${NC}"
	fi
}

is_installed() {
	dpkg -s "$1" &>/dev/null
	return $?
}

installpkg() {
  if ! is_installed "$1"; then
			sudo apt -qq install "$1" -y
			echo -e "${LINECOLOR}${solsymble}${NC}  ${CYANB}$1${NC} ${BREENB}installed${NC}"
		else
			echo -e "${LINECOLOR}${solsymble}${NC}  ${GRAYB}$1${NC} ${GRAY}already installed${NC}"
		fi
}

installnala() {
	if ! is_installed "nala"; then
		sudo apt -qq install nala -y
	fi
}

installthorium() {
	if ! is_installed "thorium-browser"; then
		wget https://dl.thorium.rocks/debian/dists/stable/thorium.list
		sudo mv thorium.list /etc/apt/sources.list.d/
		sudo apt update -y
		sudo apt install thorium-browser -y
	fi
}

installpkgs() {
	deps=(git ninja-build bsdmainutils gettext cmake unzip curl build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev wget libreadline-dev gnupg2 zsh gh vim neofetch ranger bat fzf ripgrep fd-find htop btop delta pipx kitty rbenv vim-gtk3 luarocks golang-go shellcheck figlet lolcat)
	for pkgs in ${deps[@]}; do
		installpkg "$pkgs"
	done
}

installrustup() {
	if [ ! -d "$HOME/.rustup" ]; then
		curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
	fi
}

installstarship() {
	if ! command -v starship >/dev/null 2>&1; then
		curl -sS https://starship.rs/install.sh | sh
	fi
}

installbob() {
	if [ ! -f "$HOME/.cargo/bin/bob" ]; then
		cargo install --git https://github.com/MordechaiHadad/bob.git
	fi
}

setshell() {
	if [[ $SHELL != "/usr/bin/zsh" ]]; then
  		info "Changing shell to zsh."
  		chsh -s /usr/bin/zsh
	fi
}

install_fonts() {
 createdir "$HOME/.local/share"
	symlink "$REPOS/dots/local/fonts" "$HOME/.local/share/fonts"
	fc-cache -r
}

case "$1" in
setup)
	clear
	logo
	setup_start
 	setup_link
	setup_zsh
	success "Done."
	exit
	;;
link)
	clear
	logo
	setup_link
	success "Done."
	exit
	;;
update)
	clear
	logo
	title "Updating System.                     "
	sudo apt -qq update -y && sudo apt -qq upgrade -y
	exit
	;;
fonts)
	clear
	logo
	title "Installing Fonts.                     "
	install_fonts
	success "Done."
	exit
	;;
*)
	clear
	logo
	menu
	exit
	;;
esac

# vim:ft=sh:nowrap