#!/bin/bash

REPOS="$HOME/repos"
DOTFILES="$REPOS/dots"
COLOR_GRAY="\033[1;38;5;243m"
COLOR_BLUE="\033[1;34m"
COLOR_GREEN="\033[1;32m"
COLOR_RED="\033[1;31m"
COLOR_PURPLE="\033[1;35m"
COLOR_YELLOW="\033[1;33m"
COLOR_NONE="\033[0m"

logo() {

	echo -e "${COLOR_BLUE}
  ░░░░░░   ░░░░░░  ░░░░░░░ ░░░░░░░
  ▒▒   ▒▒ ▒▒    ▒▒      ▒▒ ▒▒
  ▒▒   ▒▒ ▒▒    ▒▒    ▒▒   ▒▒▒▒▒▒▒
  ▓▓   ▓▓ ▓▓    ▓▓   ▓▓         ▓▓
  ██████   ██████    ██    ███████\n${COLOR_NONE}"
}

menu() {

	echo -e "  ${COLOR_GRAY}OPTIONS${COLOR_NONE}"
	echo -e "    ${COLOR_GREEN}setup${COLOR_NONE}"
	echo -e "    ${COLOR_GREEN}link${COLOR_NONE}"
	echo -e "    ${COLOR_GREEN}zsh${COLOR_NONE}"
	echo -e ""
}

title() {
	echo -e "\n  ${COLOR_PURPLE}$1${COLOR_NONE}"
	echo -e "  ${COLOR_GRAY}󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴${COLOR_NONE}\n"
}

error() {
	echo -e "    ${COLOR_RED} ${COLOR_NONE}$1"
	exit 1
}

warning() {
	echo -e "    ${COLOR_YELLOW} ${COLOR_NONE}$1"
}

info() {
	echo -e "    ${COLOR_BLUE} ${COLOR_NONE}$1"
}

success() {
	echo -e "  ${COLOR_GREEN}$1${COLOR_NONE}"
}

ask(){
	while true; do
		read -rp " Start the setup? [Y/n]: " yn
			case $yn in
				[Yy]* ) break;;
				[Nn]* ) exit;;
				* ) break;;
			esac
  		done
	clear
}

createdir() {
	if [ ! -d "$1" ]; then
		info "Creating $1"
		mkdir -p "$1"
	fi
}

take() {
	if [ ! -d "$2" ]; then
		info "Cloning github.com/$1 to $2"
		git clone "https://github.com/$1.git" "$2"
	fi
}

link_bin() {
	if [ ! -e "$HOME/.local/bin/$2" ]; then
			ln -s $(which $1) $HOME/.local/bin/$2
	fi
}

symlink() {
	if [ -e "$2" ]; then
		mv -fv "$2" "$2.bak"
	fi
	ln -s "$1" "$2"
	printf '    %s 󰜴 %s\n' "$1" "$2"
}

is_installed() {
	dpkg -s "$1" &>/dev/null
	return $?
}

installnala() {
	if ! is_installed "nala"; then
		sudo apt install nala -y
	fi
}

installthorium() {
	if ! is_installed "thorium-browser"; then
		wget https://dl.thorium.rocks/debian/dists/stable/thorium.list
		sudo mv thorium.list /etc/apt/sources.list.d/
		sudo apt update -y
		sudo apt install thorium-browser -y
	fi
}

installpkgs() {
	deps=(git ninja-build bsdmainutils gettext cmake unzip curl build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev wget libreadline-dev gnupg2 zsh gh vim neofetch ranger bat fzf ripgrep fd-find htop btop delta pipx kitty rbenv vim-gtk3 luarocks golang-go shellcheck)
	for pkgs in ${deps[@]}; do
		if ! is_installed "$pkgs"; then
			sudo nala install "$pkgs" -y
		else
			printf '    %s is already installed.\n' "$pkgs"
		fi
	done
}

installrustup() {
	if [ ! -d "$HOME/.rustup" ]; then
		curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
	fi
}

installstarship() {
	if ! command -v starship >/dev/null 2>&1; then
		curl -sS https://starship.rs/install.sh | sh
	fi
}

installbob() {
	if [ ! -f "$HOME/.cargo/bin/bob" ]; then
		cargo install --git https://github.com/MordechaiHadad/bob.git
	fi
}

setshell() {
	if [[ $SHELL != "/usr/bin/zsh" ]]; then
  		info "Changing shell to zsh."
  		chsh -s /usr/bin/zsh
	fi
}

installfonts() {
 createdir "$HOME/.local/share"
	symlink "$DOTFILES/local/fonts" "$HOME/.local/share/"
	fc-cache -r
}

setup_link() {
	title "Creating symlinks.."
	take "5nik7/dots" "$REPOS/dots"
	take "5nik7/starship" "$REPOS/starship"
    take "5nik7/neoviim" "$REPOS/neoviim"
	symlink "$DOTFILES/zsh/.zshrc" "$HOME/.zshrc"
	symlink "$REPOS/starship/starship.toml" "$HOME/.config/starship.toml"
	symlink "$REPOS/neoviim" "$HOME/.config/nvim"
	symlink "$DOTFILES/bat" "$HOME/.config/bat"
	symlink "$DOTFILES/kitty" "$HOME/.config/kitty"
	symlink "$DOTFILES/btop" "$HOME/.config/btop"
	symlink "$DOTFILES/bottom" "$HOME/.config/bottom"
	symlink "$DOTFILES/fsh" "$HOME/.config/fsh"
	symlink "$DOTFILES/git/.gitconfig" "$HOME/.gitconfig"
	createdir "$HOME/.config/ranger"
	symlink "$DOTFILES/ranger/rc.conf" "$HOME/.config/ranger/rc.conf"
	symlink "$DOTFILES/ranger/rifle.conf" "$HOME/.config/ranger/rifle.conf"
	symlink "$DOTFILES/ranger/commands.py" "$HOME/.config/ranger/commands.py"
	symlink "$DOTFILES/ranger/scope.sh" "$HOME/.config/ranger/scope.sh"
	take "cdump/ranger-devicons2" "$HOME/.config/ranger/plugins/devicons2"
	echo -e "\n"
}

setup_start() {
	title "Installing needed packages.."
	sudo apt update -y
	sudo apt upgrade -y	
	installnala
	installpkgs
	installrustup
	installstarship
	installbob
	installthorium
	link_bin batcat bat
	link_bin fdfind fd
	xdg-user-dirs-update
	createdir "$HOME/.local/bin"
    createdir "$HOME/bin"
	createdir "$REPOS"
	createdir "$HOME/.config"
    installfonts
	echo -e "\n"
}

setup_zsh() {
	title "Setting up zsh.."
	if [[ $SHELL = "/usr/bin/zsh" ]]; then
		warning "Default shell is already zsh."
		echo -e "\n"
	else
		installnala
		sudo nala install zsh -y
		setshell
	fi
}

case "$1" in
setup)
	clear
	logo
	setup_start
 	setup_link
	setup_zsh
	success "Done.\n"
	exit
	;;
link)
	clear
	logo
	setup_link
	success "Done.\n"
	exit
	;;
zsh)
	clear
	logo
	setup_zsh
	success "Done.\n"
	exit
	;;
*)
	clear
	logo
	menu
	exit
	;;
esac
