#!/bin/bash

REPOS="$HOME/repos"
DOTS="$REPOS/dots"
DOTFILES="$HOME/.dots"
XDG_CONFIG_HOME="$HOME/.config"
XDG_CACHE_HOME="$HOME/.cache"
XDG_DATA_HOME="$HOME/.local/share"
XDG_STATE_HOME="$HOME/.local/state"


GRAY="\033[0;30m"
WHITE="\033[0;37m"
RED="\033[0;31m"
GREEN="\033[0;32m"
BLUE="\033[0;34m"
YELLOW="\033[0;33m"
CYAN="\033[0;36m"
PURPLE="\033[0;35m"
BOLDGRAY="\033[1;30m"
BOLDWHITE="\033[1;37m"
BOLDRED="\033[1;31m"
BOLDBLUE="\033[1;34m"
BOLDGREEN="\033[1;32m"
BOLDYELLOW="\033[1;33m"
BOLDCYAN="\033[1;36m"
BOLDPURPLE="\033[1;35m"

NC="\033[0m"

HEADER="\e[1;34m"
LINECOLOR="\033[38;5;008m"

cecho(){
	GRAY="\033[0;30m"
	WHITE="\033[0;37m"
    RED="\033[0;31m"
    GREEN="\033[0;32m"
    BLUE="\033[0;34m"
    YELLOW="\033[0;33m"
    CYAN="\033[0;36m"
    PURPLE="\033[0;35m"
    BOLDGRAY="\033[1;30m"
	BOLDWHITE="\033[1;37m"
    BOLDRED="\033[1;31m"
    BOLDBLUE="\033[1;34m"
    BOLDGREEN="\033[1;32m"
    BOLDYELLOW="\033[1;33m"
    BOLDCYAN="\033[1;36m"
    BOLDPURPLE="\033[1;35m"

    NC="\033[0m"

    printf "${(P)1}${2} ${NC}\n" # <-- zsh
    # printf "${!1}${2} ${NC}\n" # <-- bash
}

logo() {
	topdoubleline
	echo -e "${LINECOLOR}\033[48;5;234m║                                        ${LINECOLOR}║
\033[48;5;233m║${HEADER}    ░░░░░░   ░░░░░░  ░░░░░░░ ░░░░░░░    ${LINECOLOR}║
\033[48;5;233m║${HEADER}    ▒▒   ▒▒ ▒▒    ▒▒      ▒▒ ▒▒         ${LINECOLOR}║
\033[48;5;232m║${HEADER}    ▒▒   ▒▒ ▒▒    ▒▒    ▒▒   ▒▒▒▒▒▒▒    ${LINECOLOR}║
\033[48;5;232m║${HEADER}    ▓▓   ▓▓ ▓▓    ▓▓   ▓▓         ▓▓    ${LINECOLOR}║
\033[48;5;016m║${HEADER}    ██████   ██████    ██    ███████    ${LINECOLOR}║
\033[48;5;016m║${HEADER}                                        ${LINECOLOR}║${NC}"
  bottomdoubleline
}

menu() {
	topline
	title "OPTIONS"
	menuopt "setup"
	menuopt "link"
	linebreak
	bottomline
}

menuopt() {
	echo -e "${LINECOLOR}│${NC}  ${GRAY}┃${NC} ${YELLOW}$1${NC}"
}

line() {
	echo -e "${GRAY}󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴󰍴${NC}"
}

thickline() {
	echo -e "${GRAY}${NC}"
}

doubleline() {
	echo -e "${GRAY}════════════════════════════════════════${NC}"
}

topline() {
	echo -e "${LINECOLOR}┌──────────────${NC}"
}

bottomline() {
	echo -e "${LINECOLOR}└──────────────${NC}"
}

topdoubleline() {
	echo -e "${LINECOLOR}\033[48;5;234m╔════════════════════════════════════════╗${NC}"
}

bottomdoubleline() {
	echo -e "${LINECOLOR}\033[48;5;016m╚════════════════════════════════════════╝${NC}"
}

dashline() {
	echo -e "${GRAY}${NC}"
}


dotline() {
	echo -e "${GRAY}${NC}"
}

texture() {
	echo -e "\e[1;30m${GRAY}󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌󰔌${NC}"
}

linebreak() {
	echo -e "${LINECOLOR}│${NC}"
}

title() {
	echo -e "${LINECOLOR}│${NC}  ${BOLDGREEN}$1${NC}"
	echo -e "${LINECOLOR}│${NC}  ${GREEN}‾‾‾‾‾‾‾${NC}"
}

print_default() {
	echo -e "$*"
}

print_info() {
	echo -e "\e[1;36m$*\e[m" # cyan
}

print_notice() {
	echo -e "\e[1;35m$*\e[m" # magenta
}

print_success() {
	echo -e "\e[1;32m$*\e[m" # green
}

print_warning() {
	echo -e "\e[1;33m$*\e[m" # yellow
}

print_error() {
	echo -e "\e[1;31m$*\e[m" # red
}

print_debug() {
	echo -e "\e[1;34m$*\e[m" # blue
}

error() {
	echo -e "    ${COLOR_RED} ${NC}$1"
}

warning() {
	echo -e "    ${COLOR_YELLOW} ${NC}$1"
}

info() {
	echo -e "    ${BLUE} ${NC}$1"
}

success() {
	echo -e "   ${BOLDGREEN}$1${NC}"
}

ask(){
	while true; do
		read -rp " Start the setup? [Y/n]: " yn
			case $yn in
				[Yy]* ) break;;
				[Nn]* ) exit;;
				* ) break;;
			esac
  		done
	clear
}

createdir() {
	if [ ! -d "$1" ]; then
		print_info "Created $1"
		mkdir -p "$1"
	fi
}

take() {
	if [ ! -d "$2" ]; then
		print_info "Cloning github.com/$1 to $2"
		git clone "https://github.com/$1.git" "$2"
	fi
}

link_bin() {
	if [ ! -e "$HOME/.local/bin/$2" ]; then
			ln -s $(which $1) $HOME/.local/bin/$2
	fi
}

symlink() {
	root=$(echo "$1" | cut -d "/" -f 1)
	if [ ! -e "$2" ]; then
		ln -s "$1" "$2"
		echo -e "   ${BOLDCYAN}$1${NC} ${BOLDGRAY}->${NC} ${BOLDCYAN}$2${NC}"
	else
		echo -e "   ${BOLDGRAY}$2 already exists${NC}"
	fi
}

backup() {
	if [ -f "$1" ]; then
		mv -f "$1" "${1}.bak"
		printf '    \nCreating backup for %s\n' "$1"	
	else
		print_warning "$2 not found"
	fi
}

is_installed() {
	dpkg -s "$1" &>/dev/null
	return $?
}

installpkg() {
  if ! is_installed "$1"; then
			sudo nala install "$1" -y
		else
			printf '    \n%s is already installed.\n' "$1"
		fi
}

installnala() {
	if ! is_installed "nala"; then
		sudo apt install nala -y
	fi
}

installthorium() {
	if ! is_installed "thorium-browser"; then
		wget https://dl.thorium.rocks/debian/dists/stable/thorium.list
		sudo mv thorium.list /etc/apt/sources.list.d/
		sudo apt update -y
		sudo apt install thorium-browser -y
	fi
}

installpkgs() {
	deps=(git ninja-build bsdmainutils gettext cmake unzip curl build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev wget libreadline-dev gnupg2 zsh gh vim neofetch ranger bat fzf ripgrep fd-find htop btop delta pipx kitty rbenv vim-gtk3 luarocks golang-go shellcheck)
	for pkgs in ${deps[@]}; do
		installpkg "$pkgs"
	done
}

installrustup() {
	if [ ! -d "$HOME/.rustup" ]; then
		curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
	fi
}

installstarship() {
	if ! command -v starship >/dev/null 2>&1; then
		curl -sS https://starship.rs/install.sh | sh
	fi
}

installbob() {
	if [ ! -f "$HOME/.cargo/bin/bob" ]; then
		cargo install --git https://github.com/MordechaiHadad/bob.git
	fi
}

setshell() {
	if [[ $SHELL != "/usr/bin/zsh" ]]; then
  		info "Changing shell to zsh."
  		chsh -s /usr/bin/zsh
	fi
}

installfonts() {
 createdir "$HOME/.local/share"
	symlink "$DOTFILES/local/fonts" "$HOME/.local/share/"
	fc-cache -r
}

setup_link() {
	title "Creating symlinks.."
	linebreak
	take "5nik7/dots" "$DOTS"
	take "5nik7/starship" "$REPOS/starship"
    take "5nik7/neoviim" "$REPOS/neoviim"
	symlink "$DOTS/dots" "$DOTFILES/dots"
	symlink "$DOTS/zsh" "$DOTFILES/zsh"
	symlink "$DOTS/git" "$DOTFILES/git"
	symlink "$DOTS/kitty" "$DOTFILES/kitty"
	symlink "$DOTS/ranger" "$DOTFILES/ranger"
	symlink "$DOTS/btop" "$DOTFILES/btop"
	symlink "$DOTS/bottom" "$DOTFILES/bottom"
	symlink "$DOTS/bat" "$DOTFILES/bat"
	symlink "$DOTS/fsh" "$DOTFILES/fsh"
	symlink "$DOTS/lsd" "$DOTFILES/lsd"
	symlink "$REPOS/starship" "$DOTFILES/starship"
	symlink "$REPOS/neoviim" "$DOTFILES/nvim"
	symlink "$DOTS/git/gitconfig" "$HOME/.gitconfig"
	symlink "$DOTS/zsh/zshrc" "$HOME/.zshrc"
	symlink "$DOTS/bat" "$XDG_CONFIG_HOME/bat"
	symlink "$DOTS/kitty" "$XDG_CONFIG_HOME/kitty"
	symlink "$DOTS/btop" "$XDG_CONFIG_HOME/btop"
	symlink "$DOTS/bottom" "$XDG_CONFIG_HOME/bottom"
	symlink "$DOTS/fsh" "$XDG_CONFIG_HOME/fsh"
	symlink "$DOTS/ranger" "$XDG_CONFIG_HOME/ranger"
	symlink "$REPOS/starship/starship.toml" "$XDG_CONFIG_HOME/starship.toml"
	symlink "$REPOS/neoviim" "$XDG_CONFIG_HOME/nvim"
	linebreak
}

setup_start() {
	title "Installing needed packages.."
	linebreak
	sudo apt update -y
	sudo apt upgrade -y	
	installnala
	installpkgs
	installrustup
	installstarship
	installbob
	installthorium
	link_bin batcat bat
	link_bin fdfind fd
	xdg-user-dirs-update
	createdir "$REPOS"
	createdir "$DOTFILES"
	createdir "$HOME/.local/bin"
    createdir "$HOME/bin"
	createdir "$XDG_CONFIG_HOME"
	createdir "$XDG_CACHE_HOME"
	createdir "$XDG_DATA_HOME"
	createdir "$XDG_STATE_HOME"
	linebreak
}

setup_zsh() {
	title "Setting up zsh.."
	if [[ $SHELL = "/usr/bin/zsh" ]]; then
		warning "Default shell is already zsh."
		linebreak
	else
		installnala
		sudo nala install zsh -y
		setshell
	fi
}

case "$1" in
setup)
	clear
	logo
	setup_start
 	setup_link
	setup_zsh
	success "Done."
	line
	exit
	;;
link)
	clear
	logo
	setup_link
	success "Done."
	line
	exit
	;;
*)
	clear
	logo
	menu
	exit
	;;
esac
