#  ╔═╗╔═╗╦ ╦╦═╗╔═╗
#  ╔═╝╚═╗╠═╣╠╦╝║
# o╚═╝╚═╝╩ ╩╩╚═╚═╝

if [ -n "${ZSH_DEBUGRC+1}" ]; then
  zmodload zsh/zprof
fi

# set global default env
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

export DOTS="${SOTS:-$HOME/dots}"

[ -r "$DOTS/bin/util" ] && source "$DOTS/bin/util"

if has nvim; then
  EDITOR='nvim'
elif has vim; then
  EDITOR='vim'
elif has vi; then
  EDITOR='vi'
elif has code; then
  EDITOR='code'
else
  EDITOR='nano'
fi

export EDITOR
export SYSTEMD_EDITOR=$EDITOR
export VISUAL="$EDITOR"
export EDITOR_TERM="$TERMINAL -e $EDITOR"

export ZSH="$DOTS/shells/zsh"
export ZSHCOMP="$ZSH/completions"
declare -xgA zsh
declare -x zsh[root]="$ZSH"
declare -x zsh[completions]="$ZSHCOMP"

environments=($DOTS/**/*.env)

for file in ${(M)environments#*/*.env}; do
  source $file
done

docs="${DOCS:-$HOME/Documents}"
export DOCS="$docs"

notes="${NOTES:-$HOME/Notes}"
export NOTES="$notes"

# set config env
export STARSHIP_CONFIG="${dot[configs]}/starship/starship.toml"
export STARSHIP_DIR="${STARSHIP_CONFIG%/*}"
export STARSHIP_THEMES="$STARSHIP_DIR/themes"

export BAT_CONFIG_DIR="${dot[configs]}/bat"
export BAT_CONFIG_PATH="$BAT_CONFIG_DIR/bat.conf"
export YAZI_CONFIG_HOME="$DOTFILES/yazi"

[ -r "$HOME/.fzf.zsh" ] && source "$HOME/.fzf.zsh"

[ -r "${XDG_DATA_HOME}/bob/env/env.sh" ] && source "${XDG_DATA_HOME}/bob/env/env.sh"

export GOBIN="${GOBIN:-$HOME/go/bin}"
autoload -U colors
colors

export CLICOLOR=1

autoload -U +X bashcompinit && bashcompinit
autoload -Uz compinit

zmodload zsh/complist
compinit
_comp_options+=(globdots)

prepath "$zsh[completions]"

fpath=($PREFIX/share/zsh/site-functions $fpath)

fpath=($zsh[completions] $fpath)

prepath "$GOBIN"
extpath "$HOME/.local/share/gem/ruby/3.4.0/bin"
prepath "$HOME/.cargo/bin"
prepath "$HOME/.local/bin" || addir "$HOME/.local/bin"
prepath "$HOME/bin"

shellmod "functions"
shellmod "aliases"
shellmod "options"
shellmod "fzf"

so "${themes[cmd]}"
set_theme 2>/dev/null

shellmod "completions"
shellmod "plugins"

so "$HOME/.cargo/env"
so "$DOTSHHHH/secrets.sh"

PYTHONSTARTUP="$HOME/.pythonrc"
if check $PYTHONSTARTUP; then
  export PYTHONSTARTUP
fi

if has zoxide; then
  eval "$(zoxide init zsh)"
  alias cd='z'
fi

if has direnv; then
  eval "$(direnv hook zsh)"
  DIRENV_LOG_FORMAT=$'\033[0;90mdirenv: %s\033[0m'
  export DIRENV_LOG_FORMAT
fi

has batpipe && eval "$(batpipe)"

has batman && eval "$(batman --export-env)"

so "$HOME/.atuin/bin/env" && has atuin && eval "$(atuin init zsh)"

has tv && eval "$(tv init zsh)"

has mise && eval "$(mise activate zsh)"

if checkdir "$HOME/.bun"; then
  export BUN_INSTALL="$HOME/.bun"
  prepath "$BUN_INSTALL/bin"
  so "$HOME/.bun/_bun"
fi

NVM_DIR="${NVM_DIR}:-$HOME/.nvm}"
if checkdir "$NVM_DIR"; then
  so "$NVM_DIR/nvm.sh"          # This loads nvm
  so "$NVM_DIR/bash_completion" # This loads nvm bash_completion
fi

RBENV="$HOME/.rbenv/bin/rbenv"
if check "$RBENV"; then
  eval "$(~/.rbenv/bin/rbenv init - --no-rehash zsh)"
fi

has usage && source <(usage g completion-init zsh)

has uv && eval "$(uv generate-shell-completion zsh)"

has uvx && eval "$(uvx --generate-shell-completion zsh)"

has ipinfo && { complete -o default -C "$HOME/go/bin/ipinfo" ipinfo; }

if has starship; then
  eval "$(starship init zsh)" && eval "$(starship completions zsh)"
fi

[ -r "${zsh[local]}" ] && source "${zsh[local]}"

# if [[ -n $HOME/.zcompdump(#qN.mh+24) ]]; then
#   compinit -d $HOME/.zcompdump
# else
#   compinit -C
# fi

compinit

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

enable-fzf-tab

reload-completion() {
  local input="$@"

  for comp in "${input[@]}"; do
    unfunction "_$comp" 2>/dev/null
    autoload -Uz "_$comp"
  done
}
alias rlc="reload-completion"

reload-completions() {
  local dump=${ZSH_COMPDUMP:-${ZDOTDIR:-$HOME}/.zcompdump}

  rm -f -- "$dump" "$dump.zwc"
  autoload -Uz compinit
  compinit -d "$dump"
}
alias rlcs="reload-completions"

if [ -n "${ZSH_DEBUGRC+1}" ]; then
  zprof
fi

# vim: set noet ft=zsh tw=4 sw=4 ff=unix
###-begin-npm-completion-###
#
# npm command completion script
#
# Installation: npm completion >> ~/.bashrc  (or ~/.zshrc)
# Or, maybe: npm completion > /usr/local/etc/bash_completion.d/npm
#

if type complete &>/dev/null; then
  _npm_completion () {
    local words cword
    if type _get_comp_words_by_ref &>/dev/null; then
      _get_comp_words_by_ref -n = -n @ -n : -w words -i cword
    else
      cword="$COMP_CWORD"
      words=("${COMP_WORDS[@]}")
    fi

    local si="$IFS"
    if ! IFS=$'\n' COMPREPLY=($(COMP_CWORD="$cword" \
                           COMP_LINE="$COMP_LINE" \
                           COMP_POINT="$COMP_POINT" \
                           npm completion -- "${words[@]}" \
                           2>/dev/null)); then
      local ret=$?
      IFS="$si"
      return $ret
    fi
    IFS="$si"
    if type __ltrim_colon_completions &>/dev/null; then
      __ltrim_colon_completions "${words[cword]}"
    fi
  }
  complete -o default -F _npm_completion npm
elif type compdef &>/dev/null; then
  _npm_completion() {
    local si=$IFS
    compadd -- $(COMP_CWORD=$((CURRENT-1)) \
                 COMP_LINE=$BUFFER \
                 COMP_POINT=0 \
                 npm completion -- "${words[@]}" \
                 2>/dev/null)
    IFS=$si
  }
  compdef _npm_completion npm
elif type compctl &>/dev/null; then
  _npm_completion () {
    local cword line point words si
    read -Ac words
    read -cn cword
    let cword-=1
    read -l line
    read -ln point
    si="$IFS"
    if ! IFS=$'\n' reply=($(COMP_CWORD="$cword" \
                       COMP_LINE="$line" \
                       COMP_POINT="$point" \
                       npm completion -- "${words[@]}" \
                       2>/dev/null)); then

      local ret=$?
      IFS="$si"
      return $ret
    fi
    IFS="$si"
  }
  compctl -K _npm_completion npm
fi
###-end-npm-completion-###
