background = "#fbf1c7"
foreground = "#3c3836"
muted = "#928374"
accent = "#8f3f71"
selection = "#d5c4a1"
error = "#9d0006"
warning = "#b57614"
info = "#076678"
hint = "#427b58"
mode = "light"
red = "#9d0006"
green = "#427b58"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#076678"
bright_red = "#9d0006"
bright_green = "#427b58"
bright_yellow = "#b57614"
bright_blue = "#076678"
bright_magenta = "#8f3f71"
bright_cyan = "#076678"
bright_foreground = "#3c3836"
dark_foreground = "#928374"
light_foreground = "#3c3836"
dark_background = "#fbf1c7"
darker_background = "#fbf1c7"
lighter_background = "#d5c4a1"
orange = "#b57614"
brown = "#928374"
