name = "Gruvbox"
default_flavor = "dark"
[roles]
background = "dark0"
foreground = "light1"
muted = "gray"
accent = "bright_purple"
selection = "dark2"
error = "bright_red"
warning = "bright_yellow"
info = "bright_blue"
hint = "bright_aqua"
[roles.light]
background = "light0"
foreground = "dark1"
muted = "gray"
accent = "faded_purple"
selection = "light2"
error = "faded_red"
warning = "faded_yellow"
info = "faded_blue"
hint = "faded_aqua"
[integrations]
nvim = "gruvbox"
