autumnGreen = "#76946A"
autumnRed = "#C34043"
autumnYellow = "#DCA561"
boatYellow2 = "#C0A36E"
carpYellow = "#E6C384"
crystalBlue = "#7E9CD8"
dragonBlue = "#658594"
fujiGray = "#727169"
fujiWhite = "#DCD7BA"
katanaGray = "#717C7C"
oldWhite = "#C8C093"
oniViolet = "#957FB8"
oniViolet2 = "#b8b4d0"
peachRed = "#FF5D62"
roninYellow = "#FF9E3B"
sakuraPink = "#D27E99"
samuraiRed = "#E82424"
springBlue = "#7FB4CA"
springGreen = "#98BB6C"
springViolet1 = "#938AA9"
springViolet2 = "#9CABCA"
sumiInk0 = "#16161D"
sumiInk1 = "#181820"
sumiInk2 = "#1a1a22"
sumiInk3 = "#1F1F28"
sumiInk4 = "#2A2A37"
sumiInk5 = "#363646"
sumiInk6 = "#54546D"
surimiOrange = "#FFA066"
waveAqua1 = "#6A9589"
waveAqua2 = "#7AA89F"
waveBlue1 = "#223249"
waveBlue2 = "#2D4F67"
waveRed = "#E46876"
winterBlue = "#252535"
winterGreen = "#2B3328"
winterRed = "#43242B"
winterYellow = "#49443C"
