background = "#e1e2e7"
foreground = "#3760bf"
muted = "#848cb5"
accent = "#9854f1"
selection = "#b7c1e3"
error = "#c64343"
warning = "#8c6c3e"
info = "#07879d"
hint = "#118c74"
mode = "light"
red = "#f52a65"
green = "#587539"
yellow = "#8c6c3e"
blue = "#2e7de9"
magenta = "#9854f1"
cyan = "#118c74"
bright_red = "#f52a65"
bright_green = "#587539"
bright_yellow = "#8c6c3e"
bright_blue = "#2e7de9"
bright_magenta = "#9854f1"
bright_cyan = "#118c74"
bright_foreground = "#3760bf"
dark_foreground = "#848cb5"
light_foreground = "#3760bf"
dark_background = "#e1e2e7"
darker_background = "#e1e2e7"
lighter_background = "#b7c1e3"
orange = "#8c6c3e"
brown = "#848cb5"
