package cli

import (
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/5nik7/dots/internal/dispatch"
	"github.com/5nik7/dots/internal/extension"
)

// zshLiteral never treats metadata or root strings as shell expressions.
func zshLiteral(s string) string { return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'" }

func renderZsh(c catalog, roots []string) []byte {
	var builtin, external []string
	for _, command := range c.Commands {
		if command.Hidden || command.Availability.Status != "available" {
			continue
		}
		routes := append([][]string{}, command.Aliases...)
		if len(command.Route) > 0 {
			routes = append(routes, command.Route)
		}
		for _, option := range command.GlobalOptions {
			routes = append(routes, []string{option})
		}
		for _, route := range routes {
			if command.Kind == "builtin" {
				builtin = append(builtin, strings.Join(route, " "))
			} else {
				external = append(external, strings.Join(route, " "))
			}
		}
	}
	var out strings.Builder
	out.WriteString("# Generated by dots completion zsh. Source after compinit; no installation.\n_dots() {\n  emulate -L zsh\n")
	array := func(name string, values []string, sort bool) {
		if sort {
			slices.Sort(values)
			values = slices.Compact(values)
		}
		fmt.Fprintf(&out, "  local -a %s=(", name)
		for _, value := range values {
			fmt.Fprintf(&out, " %s", zshLiteral(value))
		}
		out.WriteString(" )\n")
	}
	array("builtin_routes", builtin, true)
	array("external_routes", external, true)
	array("expected_roots", roots, false)
	out.WriteString(zshBody)
	return []byte(out.String())
}

func completionOutput(out, errOut io.Writer, r *dispatch.Registry, definitions []extension.Definition, roots []string) int {
	c, err := buildCatalog(r, definitions)
	if err == nil {
		data := renderZsh(c, roots)
		var n int
		n, err = out.Write(data)
		if err == nil && n != len(data) {
			err = io.ErrShortWrite
		}
	}
	if err != nil {
		fmt.Fprintln(errOut, "dots: completion output failed")
		return 1
	}
	return 0
}

const zshBody = `  local -a entered_roots routes route_tokens prefix_tokens candidates
  local item token
  local -i i=2 j match=1
  # Prefix options are pairs only, before the first command word.
  while (( i < CURRENT )) && [[ ${(Q)words[i]} == --command-dir ]]; do
    (( i + 1 < CURRENT && ${#entered_roots} < 8 )) || return 0
    item=${(Q)words[i+1]}
    [[ -n $item && $item != -* ]] || return 0
    entered_roots+=( "$item" )
    (( i += 2 ))
  done
  routes=( "${builtin_routes[@]}" )
  if (( ${#entered_roots} != ${#expected_roots} )); then
    match=0
  else
    for (( j=1; j <= ${#expected_roots}; j++ )); do
      [[ ${entered_roots[j]} == "${expected_roots[j]}" ]] || match=0
    done
  fi
  (( match )) && routes+=( "${external_routes[@]}" )
  while (( i < CURRENT )); do
    item=${(Q)words[i]}
    [[ $item != -- ]] || return 0
    prefix_tokens+=( "$item" )
    (( i++ ))
  done
  for item in "${routes[@]}"; do
    route_tokens=( ${=item} )
    (( ${#route_tokens} > ${#prefix_tokens} )) || continue
    match=1
    for (( j=1; j <= ${#prefix_tokens}; j++ )); do
      [[ ${route_tokens[j]} == "${prefix_tokens[j]}" ]] || match=0
    done
    if (( match )); then
      token=${route_tokens[${#prefix_tokens}+1]}
      [[ $token == "$PREFIX"* ]] && candidates+=( "$token" )
    fi
  done
  candidates=( "${(@ou)candidates}" )
  (( ${#candidates} )) && compadd -- "${candidates[@]}"
  return 0
}
if (( $+functions[compdef] )); then
  compdef _dots dots
fi
`
