package cli

import (
	"bytes"
	"io"
	"reflect"
	"strings"
	"testing"

	"github.com/5nik7/dots/internal/dispatch"
)

func TestCompletionContract(t *testing.T) {
	for _, args := range [][]string{{"completion"}, {"completion", "bash"}, {"completion", "zsh", "SECRET"}, {"completion", "--json"}, {"completion", "zsh", "--help"}} {
		var out, stderr bytes.Buffer
		if code := Run(args, &out, &stderr, nil, nil); code != 2 || out.Len() != 0 || stderr.Len() == 0 || strings.Contains(stderr.String(), "SECRET") {
			t.Fatal(code, out.String(), stderr.String())
		}
	}
	for _, args := range [][]string{{"completion", "--help"}, {"completion", "-h"}} {
		var out, stderr bytes.Buffer
		args = append([]string{"--command-dir", "/missing"}, args...)
		if code := Run(args, &out, &stderr, func() string { return "" }, nil); code != 0 || stderr.Len() != 0 || !strings.Contains(out.String(), "completion (zsh") {
			t.Fatal(code, out.String(), stderr.String())
		}
	}
	var out, stderr bytes.Buffer
	if Run([]string{"completion", "zsh"}, &out, &stderr, nil, nil) != 0 || stderr.Len() != 0 || !strings.HasPrefix(out.String(), "# Generated by dots completion zsh.") {
		t.Fatal(out.String(), stderr.String())
	}
	for _, w := range []catalogFailWriter{{false}, {true}} {
		stderr.Reset()
		if Run([]string{"completion", "zsh"}, w, &stderr, nil, nil) != 1 || stderr.String() != "dots: completion output failed\n" {
			t.Fatal(stderr.String())
		}
	}
}

func TestCompletionProjection(t *testing.T) {
	r, err := registry(io.Discard, io.Discard, nil, nil)
	if err != nil {
		t.Fatal(err)
	}
	c, err := buildCatalog(r, nil)
	if err != nil {
		t.Fatal(err)
	}
	m := dispatch.Metadata{ID: "synthetic", Route: []string{"nested", "child"}, Aliases: [][]string{{"compat", "child"}}}
	projected, err := projectCatalog(m, "builtin", nil)
	if err != nil {
		t.Fatal(err)
	}
	c.Commands = append(c.Commands, projected)
	hidden := projected
	hidden.Route = []string{"secret"}
	hidden.Aliases = nil
	hidden.Hidden = true
	unavailable := hidden
	unavailable.Hidden = false
	unavailable.Availability.Status = "unavailable"
	c.Commands = append(c.Commands, hidden, unavailable)
	roots := []string{"/b ' $(false)", "/a"}
	before := append([]string{}, roots...)
	got := string(renderZsh(c, roots))
	for _, want := range []string{"'nested child'", "'compat child'", "'--version'", "'completion'"} {
		if !strings.Contains(got, want) {
			t.Fatal(want)
		}
	}
	if strings.Contains(got, "'secret'") || strings.Contains(got, "'version'") || strings.Contains(got, "'--json'") || strings.Contains(got, "'zsh'") || !reflect.DeepEqual(before, roots) {
		t.Fatal(got)
	}
	if zshLiteral("a'b") != "'a'\\''b'" {
		t.Fatal("literal quote")
	}
}
