# Shell variables
# Generated by 'wal'
wallpaper="None"

# Special
background='#142444'
foreground='#E4F0FF'
cursor='#D3EEFA'

# Colors
color0='#334775'
color1='#FF5673'
color2='#00FFCC'
color3='#FFAA82'
color4='#3D81FF'
color5='#A798F0'
color6='#00E5FF'
color7='#D3EEFA'
color8='#49608D'
color9='#FF859B'
color10='#8FF8B5'
color11='#FFC990'
color12='#508FF8'
color13='#ABAFFF'
color14='#30F1EA'
color15='#E4F0FF'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
