--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/njen/.config/wpg/wallpapers/girl.jpg"

-- Special
background="#181e21"
foreground="#fdffff"
cursor="#fdffff"

-- Colors
color0="#181e21"
color1="#a39ea2"
color2="#7999aa"
color3="#aa8586"
color4="#497baa"
color5="#8a86a9"
color6="#5f84aa"
color7="#c5c6c7"
color8="#2c383e"
color9="#e8b8df"
color10="#8accef"
color11="#f0999b"
color12="#4fa0ec"
color13="#a49aef"
color14="#6aabee"
color15="#fdffff"
