[colors.primary]
background = "#181e21"
foreground = "#c5c6c7"

[colors.cursor]
text = "#181e21"
cursor = "#c5c6c7"

[colors.vi_mode_cursor]
text = "#181e21"
cursor = "#c5c6c7"

[colors.search.matches]
foreground = "#181e21"
background = "#c5c6c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#515658"
background = "#c5c6c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#181e21"
red = "#7b99aa"
green = "#497baa"
yellow = "#5f85aa"
blue = "#8983aa"
magenta = "#a39ea2"
cyan = "#aa8486"
white = "#c5c6c7"

[colors.bright]
black = "#515658"
red = "#7b99aa"
green = "#497baa"
yellow = "#5f85aa"
blue = "#8983aa"
magenta = "#a39ea2"
cyan = "#aa8486"
white = "#c5c6c7"

[colors.dim]
black = "#c5c6c7"
red = "#7b99aa"
green = "#a39ea2"
yellow = "#5f85aa"
blue = "#8983aa"
magenta = "#497baa"
cyan = "#aa8486"
white = "#515658"

