[colors.primary]
background = "#181e21"
foreground = "#fdffff"

[colors.cursor]
text = "#181e21"
cursor = "#fdffff"

[colors.vi_mode_cursor]
text = "#181e21"
cursor = "#fdffff"

[colors.search.matches]
foreground = "#181e21"
background = "#fdffff"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#2c383e"
background = "#c5c6c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#181e21"
red = "#a39ea2"
green = "#7999aa"
yellow = "#aa8586"
blue = "#497baa"
magenta = "#8a86a9"
cyan = "#5f84aa"
white = "#c5c6c7"

[colors.bright]
black = "#2c383e"
red = "#e8b8df"
green = "#8accef"
yellow = "#f0999b"
blue = "#4fa0ec"
magenta = "#a49aef"
cyan = "#6aabee"
white = "#fdffff"

[colors.dim]
black = "#fdffff"
red = "#e8b8df"
green = "#a49aef"
yellow = "#f0999b"
blue = "#4fa0ec"
magenta = "#8accef"
cyan = "#6aabee"
white = "#2c383e"

