--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#142444"
foreground="#E4F0FF"
cursor="#D3EEFA"

-- Colors
color0="#142444"
color1="#FF5673"
color2="#00FFCC"
color3="#FFAA82"
color4="#3D81FF"
color5="#A798F0"
color6="#00E5FF"
color7="#D3EEFA"
color8="#334775"
color9="#FF859B"
color10="#8FF8B5"
color11="#FFC990"
color12="#508FF8"
color13="#ABAFFF"
color14="#30F1EA"
color15="#E4F0FF"
