# Shell variables
# Generated by 'wal'
wallpaper='/home/njen/.config/wpg/wallpapers/girl.jpg'

# Special
background='#181e21'
foreground='#fdffff'
cursor='#fdffff'

# Colors
color0='#181e21'
color1='#a39ea2'
color2='#7999aa'
color3='#aa8586'
color4='#497baa'
color5='#8a86a9'
color6='#5f84aa'
color7='#c5c6c7'
color8='#2c383e'
color9='#e8b8df'
color10='#8accef'
color11='#f0999b'
color12='#4fa0ec'
color13='#a49aef'
color14='#6aabee'
color15='#fdffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
