[colors.primary]
background = "#142444"
foreground = "#e4f0ff"

[colors.cursor]
text = "#142444"
cursor = "#e4f0ff"

[colors.vi_mode_cursor]
text = "#142444"
cursor = "#e4f0ff"

[colors.search.matches]
foreground = "#142444"
background = "#e4f0ff"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#334775"
background = "#d3eefa"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#142444"
red = "#907277"
green = "#4C5370"
yellow = "#A5897F"
blue = "#375785"
magenta = "#635E70"
cyan = "#5B6789"
white = "#d3eefa"

[colors.bright]
black = "#334775"
red = "#cb838f"
green = "#56649d"
yellow = "#e9a992"
blue = "#3b6eb9"
magenta = "#7a6c9e"
cyan = "#677ec0"
white = "#e4f0ff"

[colors.dim]
black = "#e4f0ff"
red = "#cb838f"
green = "#7a6c9e"
yellow = "#e9a992"
blue = "#3b6eb9"
magenta = "#56649d"
cyan = "#677ec0"
white = "#334775"

