--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/njen/.config/wpg/wallpapers/girl.jpg"

-- Special
background="#181e21"
foreground="#c5c6c7"
cursor="#c5c6c7"

-- Colors
color0="#181e21"
color1="#7b99aa"
color2="#497baa"
color3="#5f85aa"
color4="#8983aa"
color5="#a39ea2"
color6="#aa8486"
color7="#c5c6c7"
color8="#515658"
color9="#7b99aa"
color10="#497baa"
color11="#5f85aa"
color12="#8983aa"
color13="#a39ea2"
color14="#aa8486"
color15="#c5c6c7"
