[colors.primary]
background = "#142444"
foreground = "#E4F0FF"

[colors.cursor]
text = "#142444"
cursor = "#E4F0FF"

[colors.vi_mode_cursor]
text = "#142444"
cursor = "#E4F0FF"

[colors.search.matches]
foreground = "#142444"
background = "#E4F0FF"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#334775"
background = "#D3EEFA"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#142444"
red = "#FF5673"
green = "#00FFCC"
yellow = "#FFAA82"
blue = "#3D81FF"
magenta = "#A798F0"
cyan = "#00E5FF"
white = "#D3EEFA"

[colors.bright]
black = "#334775"
red = "#FF859B"
green = "#8FF8B5"
yellow = "#FFC990"
blue = "#508FF8"
magenta = "#ABAFFF"
cyan = "#30F1EA"
white = "#E4F0FF"

[colors.dim]
black = "#E4F0FF"
red = "#FF859B"
green = "#ABAFFF"
yellow = "#FFC990"
blue = "#508FF8"
magenta = "#8FF8B5"
cyan = "#30F1EA"
white = "#334775"

