--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/njen/.config/wpg/wallpapers/Dream.jpg"

-- Special
background="#142444"
foreground="#e4f0ff"
cursor="#e4f0ff"

-- Colors
color0="#142444"
color1="#907277"
color2="#4C5370"
color3="#A5897F"
color4="#375785"
color5="#635E70"
color6="#5B6789"
color7="#d3eefa"
color8="#334775"
color9="#cb838f"
color10="#56649d"
color11="#e9a992"
color12="#3b6eb9"
color13="#7a6c9e"
color14="#677ec0"
color15="#e4f0ff"
