# Shell variables
# Generated by 'wal'
wallpaper='/home/njen/.config/wpg/wallpapers/girl.jpg'

# Special
background='#181e21'
foreground='#c5c6c7'
cursor='#c5c6c7'

# Colors
color0='#181e21'
color1='#7b99aa'
color2='#497baa'
color3='#5f85aa'
color4='#8983aa'
color5='#a39ea2'
color6='#aa8486'
color7='#c5c6c7'
color8='#515658'
color9='#7b99aa'
color10='#497baa'
color11='#5f85aa'
color12='#8983aa'
color13='#a39ea2'
color14='#aa8486'
color15='#c5c6c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
