"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# [[manager.prepend_keymap]]
# on   = "p"
# run  = "plugin smart-paste"
# desc = "Paste into the hovered directory or CWD"

[[manager.prepend_keymap]]
on = "<C-y>"
run = ["plugin system-clipboard"]

[[manager.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"
