name = "Kanagawa"
default_flavor = "wave"
[roles]
background = "sumiInk3"
foreground = "fujiWhite"
muted = "fujiGray"
accent = "oniViolet"
selection = "waveBlue1"
error = "samuraiRed"
warning = "roninYellow"
info = "dragonBlue"
hint = "waveAqua1"
[roles.dragon]
background = "dragonBlack3"
foreground = "dragonWhite"
muted = "dragonAsh"
accent = "dragonViolet"
selection = "waveBlue1"
error = "samuraiRed"
warning = "roninYellow"
info = "dragonBlue"
hint = "waveAqua1"
[roles.lotus]
background = "lotusWhite3"
foreground = "lotusInk1"
muted = "lotusGray3"
accent = "lotusViolet4"
selection = "lotusViolet3"
error = "lotusRed3"
warning = "lotusOrange2"
info = "lotusTeal3"
hint = "lotusAqua2"
[integrations]
nvim = "kanagawa"
