_nc = "#f8f0e7"
base = "#faf4ed"
foam = "#56949f"
gold = "#ea9d34"
highlight_high = "#cecacd"
highlight_low = "#f4ede8"
highlight_med = "#dfdad9"
iris = "#907aa9"
leaf = "#6d8f89"
love = "#b4637a"
muted = "#9893a5"
overlay = "#f2e9e1"
pine = "#286983"
rose = "#d7827e"
subtle = "#797593"
surface = "#fffaf3"
text = "#464261"
