export FONTPREVIEW_SEARCH_PROMPT="❯ "
export FONTPREVIEW_SIZE=532x365
export FONTPREVIEW_POSITION="+500+500"
export FONTPREVIEW_FONT_SIZE=38
export FONTPREVIEW_BG_COLOR="#151B30"
export FONTPREVIEW_FG_COLOR="#D6E4FF"
export FONTPREVIEW_PREVIEW_TEXT="ABCDEFGHIJKLM\nNOPQRSTUVWXYZ\nabcdefghijklm\nnopqrstuvwxyz\n1234567890\n!@$\%(){}[]"

# vim:ft=zsh:nowrap
