#!/usr/bin/zsh
#     _____  _____ __  ______  ______
#    /__  / / ___// / / / __ \/ ____/
#      / /  \__ \/ /_/ / /_/ / /
#   _ / /_____/ / __  / _, _/ /___
#  (_)____/____/_/ /_/_/ |_|\____/

autoload -U colors && colors
autoload -U keeper

function source_path() {
	if [ -f "$1" ]; then
		source "$1"
	fi
}

source_path "$HOME/.cache/wal/colors.sh"

export REPOS="$HOME/repos"
export DOTS="$(dirname "$(dirname "$(dirname "$(readlink "${(%):-%N}")")")")"
export DOTFILES="$(dirname "$(dirname "$(readlink "${(%):-%N}")")")"
export ZSH="$(dirname "$(readlink "${(%):-%N}")")"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CONFIG_DIRS="/etc/xdg"
export XDG_RUNTIME_DIR="/run/user/$(id -u)"
export DISPLAY=":0"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

export QT_QPA_PLATFORMTHEME=gtk2
export MOZ_ENABLE_WAYLAND=1
export GTK_IM_MODULE=gtk3
export QT_IM_MODULE=gtk3
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

export SUDO_PROMPT="passwd: "
export EDITOR='nvim'
export VISUAL=$EDITOR
export GIT_EDITOR=$EDITOR
export BROWSER="firefox"
export MANPAGER='nvim +Man!'
export PAGER='bat'
export BAT_CONFIG_PATH="$HOME/.config/bat/bat.conf"

export LESS_TERMCAP_md=$(printf "${fg_bold[green]}") \
export LESS_TERMCAP_us=$(printf "${fg[cyan]}") \
export LESS_TERMCAP_ue=$(printf "$reset_color")

export RIPGREP_CONFIG_PATH="$HOME/.config/ripgrep/rg"
export RG_DEFAULT_COMMAND="rg -i -l -p -L --hidden"

export GOBIN=$HOME/go/bin
export RUSTFLAGS="--remap-path-prefix $HOME=~"

fpath=(
    $ZSH/functions.zsh
    /usr/local/share/zsh/site-functions
    $fpath
)

if [[ -d $ZSH/functions ]]; then
    for func in $ZSH/functions/*(:t); autoload -U $func
fi

function zmodule() {
    if [ -f "$ZSH/$1.zsh" ]; then
        source "$ZSH/$1.zsh"
    fi
}

zmodule "functions"
zmodule "options"
zmodule "aliases"
zmodule "plugins"
zmodule "fzf"
zmodule "font"
zmodule "completion"

function extend_path() {
    [[ -d "$1" ]] || return

    if ! echo "$PATH" | tr ":" "\n" | grep -qx "$1"; then
	    export PATH="$1:$PATH"
    fi
}

extend_path "$DOTS/bin"
extend_path "$XDG_DATA_HOME/zsh/functions"
extend_path "$DOTFILES/bin"
extend_path "$HOME/.local/bin"
extend_path "$HOME/bin"
extend_path "$HOME/.local/share/gem/ruby/3.0.0/bin"
extend_path "$GOBIN"
extend_path "$HOME/.local/share/bob/nvim-bin"
extend_path "/mnt/c/vscode/bin"
extend_path "$HOME/.local/share/nvim/mason/bin"

bindkey -v

zle -N prepend-sudo
bindkey -M vicmd s prepend-sudo

autoload -U bashcompinit
bashcompinit

zle_highlight=('paste:none')

source_path "$HOME/.cargo/env"

# eval "$(rbenv init -)"

# eval "$(luarocks path --bin)"

# eval "$(register-python-argcomplete pipx)"

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

if [ -e /home/snikt/.nix-profile/etc/profile.d/nix.sh ]; then . /home/snikt/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

PATH="/home/snikt/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/snikt/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/snikt/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/snikt/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/snikt/perl5"; export PERL_MM_OPT;

# # Base16 Shell
# BASE16_SHELL="$HOME/.config/base16-shell/"
# [ -n "$PS1" ] && \
#     [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
#         source "$BASE16_SHELL/profile_helper.sh"

eval $(starship init zsh)
