#!/usr/bin/zsh

export REPOS="$HOME/repos"
export DOTS="$(dirname "$(dirname "$(dirname "$(readlink "${(%):-%N}")")")")"
export DOTFILES="$(dirname "$(dirname "$(readlink "${(%):-%N}")")")"
export ZSH="$(dirname "$(readlink "${(%):-%N}")")"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CONFIG_DIRS="/etc/xdg"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

export SUDO_PROMPT="passwd: "
export EDITOR='nvim'
export VISUAL=$EDITOR
export GIT_EDITOR=$EDITOR
export BROWSER="thorium-browser"
export MANPAGER='nvim +Man!'
export PAGER='bat'
export BAT_CONFIG_PATH="$HOME/.config/bat/bat.conf"
export RIPGREP_CONFIG_PATH="$HOME/.config/ripgrep/rg"
export GOPATH=$HOME/go
export GOBIN=$HOME/go/bin
export zfunc="$XDG_DATA_HOME/zsh/functions"

fpath=(
    $ZSH/functions.zsh
    $zfunc
    $fpath
)

# PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/wsl/lib"

function zmodule() {
	if [ -f "$ZSH/$1.zsh" ]; then
		source "$ZSH/$1.zsh"
	fi
}

zmodule "functions"
zmodule "options"
zmodule "theme"
zmodule "aliases"
zmodule "plugins"

function extend_path() {
    [[ -d "$1" ]] || return

    if ! echo "$PATH" | tr ":" "\n" | grep -qx "$1"; then
	    export PATH="$1:$PATH"
    fi
}

extend_path "$DOTS/bin"
extend_path "$XDG_DATA_HOME/zsh/functions"
extend_path "$HOME/.local/bin"
extend_path "$HOME/bin"
extend_path "$HOME/.local/share/gem/ruby/3.0.0/bin"
extend_path "$GOBIN"
extend_path "$HOME/.local/share/bob/nvim-bin"
extend_path "/mnt/c/vscode/bin"
extend_path "$HOME/.local/share/nvim/mason/bin"


export RG_DEFAULT_COMMAND="rg -i -l -p -L --hidden"

export FZF_DEFAULT_OPTS="
--color preview-bg:$base01
--color border:$base02
--color gutter:$base01
--color bg:$base01
--color bg+:$base00
--color fg:$base04
--color hl:$base07
--color fg+:$base09
--color hl+:$base0A
--color info:$base0E
--color prompt:$base0E
--color spinner:$base0F
--color pointer:$base0C
--color marker:$base08
--color header:$base06
--pointer='|>'
--ansi
--no-scrollbar
--info=inline
--border=sharp
--preview-window='border-sharp'"

# export FZF_DEFAULT_OPTS='--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'


# fast-theme -q XDG:catppuccin-mocha

bindkey -v

zle -N prepend-sudo
bindkey -M vicmd s prepend-sudo

autoload colors && colors

autoload -U bashcompinit
bashcompinit

function source_path() {
	if [ -f "$1" ]; then
		source "$1"
	fi
}

source_path "$HOME/.cargo/env"

# eval "$(rbenv init -)"

# eval "$(luarocks path --bin)"

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

if [ -e /home/snikt/.nix-profile/etc/profile.d/nix.sh ]; then . /home/snikt/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

eval $(starship init zsh)


PATH="/home/snikt/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/snikt/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/snikt/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/snikt/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/snikt/perl5"; export PERL_MM_OPT;
