# Shell variables
# Generated by 'wal'
wallpaper="C:/Users/njen/dev/dots/walls/Dream.jpg"

# Special
background='#151D38'
foreground='#d6e9ff'
cursor='#5500FF'

# Colors
color0='#2E3C5B'
color1='#EB6F92'
color2='#00FFCC'
color3='#FFB78D'
color4='#477EFF'
color5='#9896FF'
color6='#00FFFB'
color7='#d6e9ff'
color8='#374B72'
color9='#EB6F92'
color10='#8FF8B5'
color11='#F2C996'
color12='#5792FF'
color13='#A7A6FF'
color14='#30F1EA'
color15='#d6e9ff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
