# Shell variables
# Generated by 'wal'
wallpaper="None"

# Special
background='#1a1b26'
foreground='#c0caf5'
cursor='#c0caf5'

# Colors
color0='#15161e'
color1='#f7768e'
color2='#9ece6a'
color3='#e0af68'
color4='#7aa2f7'
color5='#bb9af7'
color6='#7dcfff'
color7='#a9b1d6'
color8='#414868'
color9='#ff899d'
color10='#9fe044'
color11='#faba4a'
color12='#8db0ff'
color13='#c7a9ff'
color14='#a4daff'
color15='#c0caf5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
