--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="C:/Users/njen/dev/dots/walls/Cat1.jpg"

-- Special
background="#1E1E2E"
foreground="#CDD6F4"
cursor="#F5E0DC"

-- Colors
color0="#45475A"
color1="#F38BA8"
color2="#A6E3A1"
color3="#F9E2AF"
color4="#89B4FA"
color5="#F5C2E7"
color6="#94E2D5"
color7="#BAC2DE"
color8="#585B70"
color9="#F38BA8"
color10="#A6E3A1"
color11="#F9E2AF"
color12="#89B4FA"
color13="#F5C2E7"
color14="#94E2D5"
color15="#A6ADC8"
