--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#1a1b26"
foreground="#c0caf5"
cursor="#c0caf5"

-- Colors
color0="#15161e"
color1="#f7768e"
color2="#9ece6a"
color3="#e0af68"
color4="#7aa2f7"
color5="#bb9af7"
color6="#7dcfff"
color7="#a9b1d6"
color8="#414868"
color9="#ff899d"
color10="#9fe044"
color11="#faba4a"
color12="#8db0ff"
color13="#c7a9ff"
color14="#a4daff"
color15="#c0caf5"
