--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="C:/Users/njen/dev/dots/walls/Dream.jpg"

-- Special
background="#151D38"
foreground="#d6e9ff"
cursor="#5500FF"

-- Colors
color0="#2E3C5B"
color1="#EB6F92"
color2="#00FFCC"
color3="#FFB78D"
color4="#477EFF"
color5="#9896FF"
color6="#00FFFB"
color7="#d6e9ff"
color8="#374B72"
color9="#EB6F92"
color10="#8FF8B5"
color11="#F2C996"
color12="#5792FF"
color13="#A7A6FF"
color14="#30F1EA"
color15="#d6e9ff"
