background = "#181616"
foreground = "#c5c9c5"
muted = "#737c73"
accent = "#8992a7"
selection = "#223249"
error = "#E82424"
warning = "#FF9E3B"
info = "#658594"
hint = "#6A9589"
mode = "dark"
red = "#E82424"
green = "#6A9589"
yellow = "#FF9E3B"
blue = "#658594"
magenta = "#8992a7"
cyan = "#658594"
bright_red = "#E82424"
bright_green = "#6A9589"
bright_yellow = "#FF9E3B"
bright_blue = "#658594"
bright_magenta = "#8992a7"
bright_cyan = "#658594"
bright_foreground = "#c5c9c5"
dark_foreground = "#737c73"
light_foreground = "#c5c9c5"
dark_background = "#181616"
darker_background = "#181616"
lighter_background = "#223249"
orange = "#FF9E3B"
brown = "#737c73"
