"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
follow_symlinks = false
command_timeout = 10000

format = """\
[\
$fill\
(\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$kubernetes\
$container\
$package\
)
$os\
$username\
$hostname\
${custom.rwd}\
${custom.dirname}\
${custom.dirname-pwsh}\
$directory\
(\
${custom.git_remote_icon}\
${custom.git_remote_icon-pwsh}\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
$git_state\
)\
(\
$fill\
)\
](bg:color_bg)
$shell$status$character"""

right_format = """
$time"""

palette = "default"

[palettes.default]

rosewater = '#f5e0dc'
flamingo = '#f2adcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'

color_ok = 'bright-green'
color_danger = 'bright-red'
color_error = 'red'
color_caution = 'bright-yellow'
color_username = ''
color_bg = 'transparent'
color_directory = 'bright-blue'
color_directory_repo = 'bright-cyan'
color_directory_readonly = 'bright-black'
color_repo_bg = 'transparent'
color_git_bracket = '#74c7ec'
color_git_remote_symbol = '#74c7ec'
color_git_username = '#74c7ec'
color_git_remote_url = '#74c7ec'
color_git_remote_repo = '#89dceb'
color_git_equal = '#585b70'
color_env = '#7f849c'
color_package = '#fab387'
color_kubernetes = 'purple'
color_docker = 'blue'
color_shell = 'black'
color_container = ''
color_other = ''
color_time = '#b4befe'
color_duration = ''
color_os = 'blue'
color_git = 'cyan'
color_git_added = 'bright-green'
color_git_deleted = 'bright-red'
color_git_branch = '#cba6f7'
color_vimcmd_ok = 'bright-black'
color_vimcmd_replace = '#eba0ac'
color_vimcmd_visual = '#cba6f7'
color_btry_bg = '#181825'
color_fill = '#313244'
color_lua = '#74c7ec'
color_rust = '#EBA0AC'
color_node = 'bright-green'

[status]
disabled = true
# format = '( [$status]($style))'
format = '([$symbol( $common_meaning)( $signal_name)]($style))'
map_symbol = true
pipestatus = true
# symbol = ''
symbol = '󰅙'
# symbol = ''
success_symbol = ''
not_found_symbol = ''
not_executable_symbol = '󰜺'
# not_executable_symbol = '󰂭'
# sigint_symbol = ''
sigint_symbol = '󰐊'
signal_symbol = '󱐋'
style = 'fg:color_error'
recognize_signal_code = true

[time]
disabled = true
time_format = "%-I:%M%P"
style = "fg:color_time"
format = '( [$time]($style) )'
# format = '( [ $time]($style) )'

[cmd_duration]
format = "([](bright-black)[ $duration]($style))"
style = "bright-black"
disabled = true

[username]
style_user = 'white'
style_root = 'white bold'
format = '[$user]($style)'
disabled = true
show_always = true
# aliases = { "Administrator" = "admin" }

[hostname]
ssh_only = true
format = '([@](white)[$hostname](white))[:](bright-white dimmed)([$ssh_symbol ](style))'
style = "bright-white"
# trim_at = '.companyname.com'
trim_at = "-"
disabled = false
ssh_symbol = "  "

[fill]
disabled = false
# symbol = ''
# symbol = ''
# symbol = '󰖰'
# symbol = ''
# symbol = ''
# symbol = '󰍴'
# symbol = '─'
# symbol = '━'
# symbol = '═'
# symbol = '╌'
symbol = ' '
style = 'fg:color_fill bg:color_bg'

[directory]
before_repo_root_style = 'fg:color_directory'
style = 'fg:color_directory'
format = '[$path]($style)( [$read_only]($read_only_style))'
repo_root_style = 'fg:sky bold'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path](fg:sapphire)( [$read_only]($read_only_style))'
truncate_to_repo = true
truncation_length = 10
fish_style_pwd_dir_length = 1
# repo_root_style = "fg:color_directory_repo bold"
# read_only = ""
read_only = "󰌾"
home_symbol = "~"
use_os_path_sep = false
use_logical_path = false
read_only_style = 'fg:color_directory dimmed'
# truncation_symbol = "…/"

[git_branch]
symbol = ''
format = '( [$symbol$branch]($style) )'
style = 'fg:color_git_branch'

[git_commit]
style = "fg:color_git"
format = "([($tag)(@$hash)]($style) )"
commit_hash_length = 7
only_detached = true
tag_symbol = "󰓼 "
tag_disabled = false
disabled = false

[git_status]
style = "fg:color_git"
format = '([$ahead_behind]($style) )([$all_status]($style) )'
stashed = "*${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
up_to_date = ""
diverged = "⇡${ahead_count}⇣${behind_count}"
conflicted = "=${count}"
deleted = "×${count}"
renamed = "»${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"
ignore_submodules = false
disabled = false

[git_metrics]
format = '([([+$added]($added_style))([-$deleted]($deleted_style))](fg:color_git) )'
added_style = "fg:color_git_added"
deleted_style = "fg:color_git_deleted"
only_nonzero_diffs = true
disabled = false

[git_state]
style = "fg:color_danger"
format = '([$state( $progress_current/$progress_total)]($style bold) )'
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
disabled = false

[nodejs]
symbol = ""
# style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[c]
symbol = ""
# style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[rust]
symbol = "󱘗"
# style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[golang]
symbol = "󰟓"
# style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[php]
symbol = ""
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[java]
symbol = ""
# style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[kotlin]
symbol = ""
# style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[haskell]
symbol = ""
# style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[python]
symbol = ""
# style = "fg:color_env"
format = '( [$symbol( $version)( $virtualenv)]($style) )'
version_format = '${raw}'

[package]
disabled = false
symbol = "󰏗"
# style = "fg:peach"
format = '( [$symbol( $version)]($style) )'

[docker_context]
symbol = ""
# style = "fg:color_docker"
format = '( [$symbol( $context)]($style) )'

[kubernetes]
symbol = "󱃾"
# style = "fg:color_kubernetes"
format = '( [($symbol( $cluster))]($style) )'
disabled = false

[lua]
detect_folders = []
style = 'fg:color_lua'
symbol = " "
format = '([${symbol}([$version](fg:color_lua)) ]($style))'

[os]
disabled = true
style = "fg:color_os"
format = '[$symbol ]($style)'

[os.symbols]
Alpaquita = ""
Alpine = ""
AlmaLinux = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "󰛓"
Gentoo = ""
HardenedBSD = "󰞌"
Illumos = "󰈸"
Kali = " "
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
OpenBSD = "󰈺"
openSUSE = ""
OracleLinux = "󰌷"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
RockyLinux = ""
Redox = "󰀘"
Solus = "󰠳"
SUSE = ""
Ubuntu = ""
Unknown = ""
Void = ""
Windows = "󰍲"
# Windows = "󰚌"
# Windows = ""
# Windows = "󰖳"
# Windows = ""


[perl]
symbol = " "

[pijul_channel]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "

[aws]
symbol = "  "

[buf]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[guix_shell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[ocaml]
symbol = " "

[line_break]
disabled = false

[shell]
format = '[$indicator]($style)'
fish_indicator = 'fish'
powershell_indicator = 'PS'
bash_indicator = ''
zsh_indicator = 'zsh'
cmd_indicator = 'cmd'
unknown_indicator = ''
style = 'bg:none fg:lavender'
disabled = true

[character]
success_symbol = '[](fg:color_ok bold)'
error_symbol = '[](fg:color_danger bold)'
vimcmd_symbol = '[▎](fg:color_vimcmd_ok)'
# vimcmd_symbol = '[](fg:color_vimcmd_ok)'
format = '$symbol '

[directory.substitutions]
"C:/" = "/"
"/data/data/com.termux/files/usr" = "/usr"
# "/storage/emulated/0" = "/storage"

[custom.dirname]
description = "dir path"
when = '[ ! $STARSHIP_SHELL == "pwsh" ] && git rev-parse --show-toplevel 2>/dev/null'
command = """
dir=$(dirout -j $(git rev-parse --show-toplevel 2>/dev/null))
echo "$dir"
"""
style = "fg:color_directory"
format = '[$output]($style)'
shell = ["bash", "--noprofile", "--norc"]

[custom.dirname-pwsh]
description = "dir path"
when = 'git rev-parse --show-toplevel 2>$null'
command = """
$dir = (($PWD).Path).Replace((Get-Item $PWD).BaseName, "").Replace("$HOME", "~").Replace("\\", "/")
Write-Output $dir
"""
style = "fg:color_directory"
format = '[$output]($style)'
shell = ["pwsh", "-NoProfile", "-Command", "-"]

[custom.rwd]
description = "cwd"
when = true
command = "rwd"
style = "fg:color_directory"
format = '([$output[->](bright-black bold)]($style))'
shell = ["bash", "--noprofile", "--norc"]

[custom.git_remote_icon]
description = "Git host icon"
when = '[ ! $STARSHIP_SHELL == "pwsh" ] && git remote get-url origin 2>/dev/null'
command = """
echo "$(git-it -i)"
"""
format = '( [$output]($style))'
style = 'fg:color_git_branch'
shell = ["bash", "--noprofile", "--norc"]

[custom.git_remote_icon-pwsh]
disabled = false
description = "Git host icon"
shell = ["pwsh", "-NoProfile", "-Command", "-"]
when = true
command = """
$icon = (git-it -i 2>$null)
Write-Host $icon
"""
format = '( [$output]($style))'
style = 'fg:color_git_branch'
