background = "#191724"
foreground = "#e0def4"
muted = "#6e6a86"
accent = "#c4a7e7"
selection = "#403d52"
error = "#eb6f92"
warning = "#f6c177"
info = "#9ccfd8"
hint = "#31748f"
mode = "dark"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#9ccfd8"
bright_red = "#eb6f92"
bright_green = "#31748f"
bright_yellow = "#f6c177"
bright_blue = "#9ccfd8"
bright_magenta = "#c4a7e7"
bright_cyan = "#9ccfd8"
bright_foreground = "#e0def4"
dark_foreground = "#6e6a86"
light_foreground = "#e0def4"
dark_background = "#191724"
darker_background = "#191724"
lighter_background = "#403d52"
orange = "#f6c177"
brown = "#6e6a86"
