#!/usr/bin/env bash

declare -r esc=$'\033'
declare -r c_reset="${esc}[0m"
declare -r c_red="${esc}[31m"
declare -r c_green="${esc}[32m"
declare -r c_yellow="${esc}[33m"
declare -r c_blue="${esc}[34m"
declare -r c_black="${esc}[30m"
declare -r rocket=" "

err() { printf "${c_red}%s %s${c_reset}\n" "$rocket" "$*" >&2; }
die() {
  err "$*"
  exit 1
}

ok() {
  printf "${c_green}%s %s${c_reset}\n" "$rocket" "$*"
}

has() {
  local verbose=0
  if [[ $1 == '-v' ]]; then
    verbose=1
    shift
  fi
  for c; do
    c="${c%% *}"
    if ! command -v "$c" &>/dev/null; then
      ((verbose)) && err "$c not found"
      return 1
    fi
  done
}

has -v starship || die "starship command found"

rockeship() {
  cat <<'EOF'
      ,
     / \
    / _ \
   |.o '.|
   |'._.'|
   |     |
 .'|  |  |'.
/  |  |  |  \
|,-'--|--'-.|
EOF
}

usage() {
  local prog=${0##*/}
  cat <<-EOF
Usage: $prog [options]

Options:
  -t, --theme
      set the starship theme

  -l --list
      list all available themes

  -h, --help
      Show this help message
EOF
}

path_display() {
  local p=$1
  if ((raw)); then
    printf '%s\n' "$p"
  else
    case "$p" in
    "$HOME")
      printf '~\n'
      ;;
    "$HOME"/*)
      printf '~/%s\n' "${p#"$HOME"/}"
      ;;
    *)
      printf '%s\n' "$p"
      ;;
    esac
  fi
}

checkdir() {
  local dir
  for dir in "$@"; do
    [ -d "$dir" ] || {
      local opath=$(path_display "$dir")
      if ask "$sir does not exist. Create it?" Y; then
        mkdir -p "$dir" && ok "$opath created"
        return 0
      else
        die "$opath not created"
      fi
    }
  done
  return 0
}

ask() {
  # https://djm.me/ask
  local prompt default reply

  while true; do

    if [ "${2:-}" = "Y" ]; then
      prompt="Y/n"
      default=Y
    elif [ "${2:-}" = "N" ]; then
      prompt="y/N"
      default=N
    else
      prompt="y/n"
      default=
    fi

    echo -e -n "$1 [$prompt] "
    read -r reply </dev/tty

    if [ -z "$reply" ]; then
      reply=$default
    fi

    case "$reply" in
    Y* | y*) return 0 ;;
    N* | n*) return 1 ;;
    esac

  done
}

config="$STARSHIP_CONFIG"

if [[ -z $config ]]; then
  config="$HOME/.config/starship.toml"
fi

cdir="$(dirname "$config")"

tdir="$STARSHIP_THEMES"

if [[ -z "$tdir" ]]; then
  tdir="$HOME/.config/starship/themes"
fi

current="$(readlink "$config")"

themes=(${tdir}/*)
presets=$(starship preset --list)

list_themes() {
  current=$(basename "$current")
  current="${current%%.*}"
  echo "themes:"
  for theme in "${themes[@]}"; do
    theme=$(basename "$theme")
    theme="${theme%%.*}"
    if [[ "$current" == "$theme" ]]; then
      theme="${c_green}${theme}${c_reset} (current)"
    fi
    if ! echo $presets | grep $theme &>/dev/null; then
      printf "%s\n" "$theme"
    fi
  done
  echo "presets:"
  for preset in "${presets[@]}"; do
    printf "%s\n" "$preset"
  done
  echo
}

main() {
  if [[ $# -eq 0 ]]; then
    usage
    exit 0
  fi

  while [[ $# -gt 0 ]]; do
    case "$1" in
    -h | --help)
      usage
      exit 0
      ;;
    -l | --list)
      list_themes
      shift
      ;;
    -t | --theme)
      if [[ -z "$2" ]]; then
        err "No theme specified"
        usage
        exit 1
      fi
      theme="$2"
      exit 0
      ;;
    *)
      err "Unknown option: $1"
      usage
      exit 1
      ;;
    esac
  done
}

main "$@"
