#!/usr/bin/env bash

main() {
  local p
  local slash='/'
  local raw=0
  if [[ $1 == '-r' ]]; then
    raw=1
    shift
  fi
  for p in "$@"; do
    p=$(dirname "$p")
    if ((raw)); then
      printf '%s\n' "$p"
    else
      case "$p" in
      "$HOME")
        printf '~%s\n' "$slash"
        ;;
      "$HOME"/*)
        printf '~/%s%s\n' "${p#"$HOME"/}" "$slash"
        ;;
      *)
        printf '%s%s\n' "$p" "$slash"
        ;;
      esac
    fi
  done
}

main "$@"
