#!/usr/bin/env bash

declare -r esc=$'\033'
declare -r rst="${esc}[0m"
declare -r black="${esc}[30m"
declare -r red="${esc}[31m"
declare -r green="${esc}[32m"
declare -r yellow="${esc}[33m"
declare -r blue="${esc}[34m"
declare -r magenta="${esc}[35m"
declare -r cyan="${esc}[36m"
declare -r white="${esc}[37m"
declare -r bold="${esc}[1m"
declare -r dim="${esc}[2m"
declare -r italic="${esc}[3m"
declare -r underline="${esc}[4m"
declare -r rev="${esc}[7m"
declare -r c21="${esc}[38;5;021m"
declare -r c22="${esc}[38;5;022m"

main() {
  (env | sed "s/=/…/") | fzf --smart-case \
    --prompt '󰇁󰅂 ' \
    --height '100%' \
    --ansi --cycle \
    --color="preview-label:2,prompt:6,preview-bg:#181825,preview-border:#181825" \
    -d … \
    --with-nth '{1}' \
    --preview-window='default:50%:down:wrap-word:border-sharp' \
    --preview-label-pos 'top' \
    --preview "printf '${c21}%s${rst}\n${bold}%s${rst}' {1} {2}" \
    --query "${1:-}" \
    --accept-nth '{1}={2}'
}

main "$@"
