#!/usr/bin/env bash

declare -r esc=$'\033'
declare -r rst="${esc}[0m"
declare -r black="${esc}[30m"
declare -r red="${esc}[31m"
declare -r green="${esc}[32m"
declare -r yellow="${esc}[33m"
declare -r blue="${esc}[34m"
declare -r magenta="${esc}[35m"
declare -r cyan="${esc}[36m"
declare -r white="${esc}[37m"
declare -r bold="${esc}[1m"
declare -r dim="${esc}[2m"
declare -r italic="${esc}[3m"
declare -r underline="${esc}[4m"
declare -r rev="${esc}[7m"

output=''

figfonts() {
  local dir=$(command figlet -I2)
  find $dir -type f -name '*.flf' -printf '%f\n' | cut -d. -f1 | sort 2>/dev/null
}

main() {
  local cmd
  local pipe=0
  local text='test'
  local preview
  while (($#)); do
    case $1 in
    -p | --pipe)
      pipe=1
      cmd=$2
      shift 2
      ;;
    *) break ;;
    esac
  done

  [[ -n $1 ]] && text="$*"

  if ((pipe)); then
    preview="figlet -f {} ${text} | $cmd"
  else
    preview="figlet -f {} ${text}"
  fi

  local output=$(figlet -f "$(figfonts | fzf --smart-case --cycle \
    --prompt "$text󰅂 " \
    --height '100%' \
    --color="preview-label:2,prompt:6,preview-bg:#181825,preview-border:#181825" \
    --preview-window='default:down:50%:wrap-word:border-sharp' --preview="$preview")" "$text" 2>/dev/null)
  [[ ! -n "$output" ]] || echo -e "$output" | cpy && echo "$output"
}

main "$@"
