#!/usr/bin/env bash

prog=${0##*/}

declare -r esc=$'\033'
declare -r rst="${esc}[0m"
declare -r black="${esc}[30m"
declare -r red="${esc}[31m"
declare -r green="${esc}[32m"
declare -r yellow="${esc}[33m"
declare -r blue="${esc}[34m"
declare -r magenta="${esc}[35m"
declare -r cyan="${esc}[36m"
declare -r white="${esc}[37m"
declare -r bold="${esc}[1m"
declare -r dim="${esc}[2m"
declare -r italic="${esc}[3m"
declare -r underline="${esc}[4m"
declare -r rev="${esc}[7m"

err() { printf "${red}%s %s${rst}\n" "[ERROR]" "$*" >&2; }
die() {
  err "$*"
  exit 1
}

has() {
  local verbose=0
  if [[ $1 == '-v' ]]; then
    verbose=1
    shift
  fi
  for c; do
    c="${c%% *}"
    if ! command -v "$c" &>/dev/null; then
      ((verbose)) && err "$c not found"
      return 1
    fi
  done
}

chcmd() {
  "$@" &>/dev/null && "$@"
}

usage() {
  local prog=${0##*/}
  IFS= read -d '' -r usage <<-EOF
	Usage: ${prog} [options] [...]

	Description...

	Options
	  -h, --help     Print this message and exit
	EOF
  echo "$usage"
}

main() {

  if [[ $# == 0 ]]; then
    usage
    exit 0
  fi

  while [[ $# -gt 0 ]]; do
    case "$1" in
    -h | --help)
      usage
      exit
      ;;
    -* | --*)
      echo "$1"
      exit
      ;;
    *)
      die "$*"
      ;;
    esac
  done
}

main "$@"
