#! /usr/bin/env bash

set -o pipefail

declare -r esc=$'\033'
declare -r c_reset="${esc}[0m"
declare -r c_red="${esc}[31m"
declare -r c_green="${esc}[32m"
declare -r c_yellow="${esc}[33m"
declare -r c_blue="${esc}[34m"
declare -r c_black="${esc}[30m"

err() { printf "${c_red}%s${c_reset}\n" "$*" >&2; }
die() {
  err "$*"
  exit 1
}

openurl() {
  if [[ "$*" == http://* ]]; then
    die "$* Npt Secure"
  elif [[ "$*" == https://* ]]; then
    termux-open-url "$*"
    exit 0
  else
    termux-open-url "https://$*"
    exit 0
  fi
}

check_git_out() {
  local ingit=$(command git rev-parse --is-inside-work-tree 2>/dev/null)

  if [[ "$ingit" = true ]]; then
    GIT_REMOTE=$(command git remote get-url origin 2>/dev/null)
    if [[ -z "$GIT_REMOTE" ]]; then
      GIT_REMOTE=$(command git ls-remote --get-url 2>/dev/null)
    fi
    GIT_REMOTE_URL=$(echo $GIT_REMOTE | sed -E "s/^https?:\\/\\/(.+@)?//; s/\\.git$//; s/\\.git$//; s/.+@(.+):([[:digit:]]+)\\/(.+)$/\\1\\/\\3/; s/.+@(.+):(.+)$/\\1\\/\\2/; s/\\/$//")
    openurl "$GIT_REMOTE_URL"
  fi
}

main() {
  local ingit query

  [ "$#" -gt 0 ] || {

    check_git_out

    if [[ ! -z "$WWW" ]]; then
      openurl "$WWW"
    fi

    openurl "https://google.com"

  }
  while [ "$#" -gt 0 ]; do
    case $1 in
    ':' | '?' | -q | --query)
      shift
      if (($# == 0)); then
        openurl "https://google.com"
      else
        local query="$@"
        openurl "https://www.google.com/search?q=${query[@]}"
      fi
      ;;
    *)
      openurl "$*"
      ;;
    esac
  done
}

main "$@"
