[colors]
foreground = "#F7F9FF"
background = "#142444"
cursor_bg = "#B0FF9D"
cursor_border = "#B0FF9D"
cursor_fg = "#101229"
selection_bg = "#304563"
selection_fg = "#E5F0FF"
split = "#334775"
compose_cursor = "#B0FF9D"
scrollbar_thumb = "#292e42"

ansi = [
  "#334775",
  "#FF5673",
  "#00FFCC",
  "#FFAA82",
  "#3D81FF",
  "#A798F0",
  "#00E5FF",
  "#F5F9FF",
]
brights = [
  "#49608D",
  "#FF859B",
  "#8FF8B5",
  "#FFC990",
  "#508FF8",
  "#ABAFFF",
  "#30F1EA",
  "#F7F9FF",
]

[colors.tab_bar]
inactive_tab_edge = "#132243"
background = "#142444"

[colors.tab_bar.active_tab]
fg_color = "#132243"
bg_color = "#4785FF"

[colors.tab_bar.inactive_tab]
fg_color = "#505d7f"
bg_color = "#292e42"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#4785FF"
bg_color = "#263054"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#4785FF"
bg_color = "#142444"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#4785FF"
bg_color = "#142444"

[metadata]
aliases = []
author = "njen"
name = "dream"
