[colors]
foreground = "#E5F0FF"
background = "#142444"
cursor_bg = "#BBC1FB"
cursor_border = "#BBC1FB"
cursor_fg = "#142444"
selection_bg = "#304563"
selection_fg = "#E5F0FF"
split = "#4785FF"
compose_cursor = "#F5C387"
scrollbar_thumb = "#292e42"

ansi = [
    "#334775",
    "#FF5674",
    "#00FFCC",
    "#F5C387",
    "#4785FF",
    "#9B99FF",
    "#0DFFFF",
    "#a9b1d6",
]
brights = [
    "#49608D",
    "#FF5674",
    "#00FFCC",
    "#F5C387",
    "#4785FF",
    "#9B99FF",
    "#0DFFFF",
    "#E5F0FF",
]

[colors.tab_bar]
inactive_tab_edge = "#132243"
background = "#142444"

[colors.tab_bar.active_tab]
fg_color = "#132243"
bg_color = "#4785FF"

[colors.tab_bar.inactive_tab]
fg_color = "#505d7f"
bg_color = "#292e42"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#4785FF"
bg_color = "#263054"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#4785FF"
bg_color = "#142444"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#4785FF"
bg_color = "#142444"

[metadata]
aliases = []
author = "njen"
name = "dream"
