-- Hilbish environment colors; load the rendered file with dofile().
-- Gum Style (generic) Variables
os.setenv("FOREGROUND", "{{ foreground }}")
os.setenv("BACKGROUND", "{{ background }}")
os.setenv("BORDER_FOREGROUND", "{{ accent }}")
os.setenv("BORDER_BACKGROUND", "{{ background }}")

-- Gum Confirm Style Variables
os.setenv("GUM_CONFIRM_PROMPT_FOREGROUND", "{{ accent }}")
os.setenv("GUM_CONFIRM_PROMPT_BACKGROUND", "{{ background }}")
os.setenv("GUM_CONFIRM_SELECTED_FOREGROUND", "{{ selection_foreground }}")
os.setenv("GUM_CONFIRM_SELECTED_BACKGROUND", "{{ selection_background }}")
os.setenv("GUM_CONFIRM_UNSELECTED_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_CONFIRM_UNSELECTED_BACKGROUND", "{{ background }}")

-- Gum Input Style Variables
os.setenv("GUM_INPUT_PROMPT_FOREGROUND", "{{ accent }}")
os.setenv("GUM_INPUT_PROMPT_BACKGROUND", "{{ background }}")
os.setenv("GUM_INPUT_PLACEHOLDER_FOREGROUND", "{{ muted }}")
os.setenv("GUM_INPUT_PLACEHOLDER_BACKGROUND", "{{ background }}")
os.setenv("GUM_INPUT_CURSOR_FOREGROUND", "{{ bright_foreground }}")
os.setenv("GUM_INPUT_CURSOR_BACKGROUND", "{{ background }}")
os.setenv("GUM_INPUT_HEADER_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_INPUT_HEADER_BACKGROUND", "{{ background }}")

-- Gum Choose Style Variables
os.setenv("GUM_CHOOSE_CURSOR_FOREGROUND", "{{ accent }}")
os.setenv("GUM_CHOOSE_CURSOR_BACKGROUND", "{{ background }}")
os.setenv("GUM_CHOOSE_HEADER_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_CHOOSE_HEADER_BACKGROUND", "{{ background }}")
os.setenv("GUM_CHOOSE_ITEM_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_CHOOSE_ITEM_BACKGROUND", "{{ background }}")
os.setenv("GUM_CHOOSE_SELECTED_FOREGROUND", "{{ selection_foreground }}")
os.setenv("GUM_CHOOSE_SELECTED_BACKGROUND", "{{ selection_background }}")

-- Gum Filter Style Variables
os.setenv("GUM_FILTER_PROMPT_FOREGROUND", "{{ accent }}")
os.setenv("GUM_FILTER_PROMPT_BACKGROUND", "{{ background }}")
os.setenv("GUM_FILTER_TEXT_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_FILTER_TEXT_BACKGROUND", "{{ background }}")
os.setenv("GUM_FILTER_MATCH_FOREGROUND", "{{ accent }}")
os.setenv("GUM_FILTER_CURSOR_TEXT_FOREGROUND", "{{ bright_foreground }}")
os.setenv("GUM_FILTER_CURSOR_TEXT_BACKGROUND", "{{ background }}")
os.setenv("GUM_FILTER_SELECTED_FOREGROUND", "{{ selection_foreground }}")
os.setenv("GUM_FILTER_SELECTED_BACKGROUND", "{{ selection_background }}")
os.setenv("GUM_FILTER_INDICATOR_FOREGROUND", "{{ accent }}")
os.setenv("GUM_FILTER_HEADER_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_FILTER_MATCH_BACKGROUND", "{{ background }}")
os.setenv("GUM_FILTER_HEADER_BACKGROUND", "{{ background }}")
os.setenv("GUM_FILTER_PLACEHOLDER_FOREGROUND", "{{ muted }}")
os.setenv("GUM_FILTER_PLACEHOLDER_BACKGROUND", "{{ background }}")
os.setenv("GUM_FILTER_INDICATOR_BACKGROUND", "{{ background }}")
os.setenv("GUM_FILTER_SELECTED_PREFIX_FOREGROUND", "{{ selection_foreground }}")
os.setenv("GUM_FILTER_SELECTED_PREFIX_BACKGROUND", "{{ selection_background }}")
os.setenv("GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND", "{{ muted }}")
os.setenv("GUM_FILTER_UNSELECTED_PREFIX_BACKGROUND", "{{ background }}")

-- Gum Table Style Variables
os.setenv("GUM_TABLE_HEADER_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_TABLE_HEADER_BACKGROUND", "{{ background }}")
os.setenv("GUM_TABLE_CELL_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_TABLE_CELL_BACKGROUND", "{{ background }}")
os.setenv("GUM_TABLE_BORDER_FOREGROUND", "{{ muted }}")
os.setenv("GUM_TABLE_BORDER_BACKGROUND", "{{ background }}")
os.setenv("GUM_TABLE_SELECTED_FOREGROUND", "{{ selection_foreground }}")
os.setenv("GUM_TABLE_SELECTED_BACKGROUND", "{{ selection_background }}")

-- Gum Spin Style Variables
os.setenv("GUM_SPIN_SPINNER_FOREGROUND", "{{ accent }}")
os.setenv("GUM_SPIN_SPINNER_BACKGROUND", "{{ background }}")
os.setenv("GUM_SPIN_TITLE_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_SPIN_TITLE_BACKGROUND", "{{ background }}")

-- Gum File Style Variables
os.setenv("GUM_FILE_CURSOR_FOREGROUND", "{{ bright_foreground }}")
os.setenv("GUM_FILE_CURSOR_BACKGROUND", "{{ background }}")
os.setenv("GUM_FILE_SYMLINK_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_FILE_SYMLINK_BACKGROUND", "{{ background }}")
os.setenv("GUM_FILE_DIRECTORY_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_FILE_DIRECTORY_BACKGROUND", "{{ background }}")
os.setenv("GUM_FILE_FILE_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_FILE_FILE_BACKGROUND", "{{ background }}")
os.setenv("GUM_FILE_PERMISSIONS_FOREGROUND", "{{ muted }}")
os.setenv("GUM_FILE_PERMISSIONS_BACKGROUND", "{{ background }}")
os.setenv("GUM_FILE_SELECTED_FOREGROUND", "{{ selection_foreground }}")
os.setenv("GUM_FILE_SELECTED_BACKGROUND", "{{ selection_background }}")
os.setenv("GUM_FILE_FILE_SIZE_FOREGROUND", "{{ muted }}")
os.setenv("GUM_FILE_FILE_SIZE_BACKGROUND", "{{ background }}")
os.setenv("GUM_FILE_HEADER_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_FILE_HEADER_BACKGROUND", "{{ background }}")

-- Gum Pager Style Variables
os.setenv("GUM_PAGER_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_PAGER_BACKGROUND", "{{ background }}")
os.setenv("GUM_PAGER_LINE_NUMBER_FOREGROUND", "{{ muted }}")
os.setenv("GUM_PAGER_LINE_NUMBER_BACKGROUND", "{{ background }}")
os.setenv("GUM_PAGER_MATCH_FOREGROUND", "{{ accent }}")
os.setenv("GUM_PAGER_MATCH_BACKGROUND", "{{ background }}")
os.setenv("GUM_PAGER_MATCH_HIGH_FOREGROUND", "{{ accent }}")
os.setenv("GUM_PAGER_MATCH_HIGH_BACKGROUND", "{{ background }}")
os.setenv("GUM_PAGER_HELP_FOREGROUND", "{{ muted }}")
os.setenv("GUM_PAGER_HELP_BACKGROUND", "{{ background }}")

-- Gum Write Style Variables
os.setenv("GUM_WRITE_BASE_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_WRITE_BASE_BACKGROUND", "{{ background }}")
os.setenv("GUM_WRITE_CURSOR_LINE_NUMBER_FOREGROUND", "{{ muted }}")
os.setenv("GUM_WRITE_CURSOR_LINE_NUMBER_BACKGROUND", "{{ background }}")
os.setenv("GUM_WRITE_CURSOR_LINE_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_WRITE_CURSOR_LINE_BACKGROUND", "{{ selection_background }}")
os.setenv("GUM_WRITE_CURSOR_FOREGROUND", "{{ bright_foreground }}")
os.setenv("GUM_WRITE_CURSOR_BACKGROUND", "{{ background }}")
os.setenv("GUM_WRITE_END_OF_BUFFER_FOREGROUND", "{{ muted }}")
os.setenv("GUM_WRITE_END_OF_BUFFER_BACKGROUND", "{{ background }}")
os.setenv("GUM_WRITE_LINE_NUMBER_FOREGROUND", "{{ muted }}")
os.setenv("GUM_WRITE_LINE_NUMBER_BACKGROUND", "{{ background }}")
os.setenv("GUM_WRITE_HEADER_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_WRITE_HEADER_BACKGROUND", "{{ background }}")
os.setenv("GUM_WRITE_PLACEHOLDER_FOREGROUND", "{{ muted }}")
os.setenv("GUM_WRITE_PLACEHOLDER_BACKGROUND", "{{ background }}")
os.setenv("GUM_WRITE_PROMPT_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_WRITE_PROMPT_BACKGROUND", "{{ background }}")

-- Gum Log Style Variables
os.setenv("GUM_LOG_LEVEL_FOREGROUND", "{{ accent }}")
os.setenv("GUM_LOG_LEVEL_BACKGROUND", "{{ background }}")
os.setenv("GUM_LOG_TIME_FOREGROUND", "{{ muted }}")
os.setenv("GUM_LOG_TIME_BACKGROUND", "{{ background }}")
os.setenv("GUM_LOG_PREFIX_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_LOG_PREFIX_BACKGROUND", "{{ background }}")
os.setenv("GUM_LOG_MESSAGE_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_LOG_MESSAGE_BACKGROUND", "{{ background }}")
os.setenv("GUM_LOG_KEY_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_LOG_KEY_BACKGROUND", "{{ background }}")
os.setenv("GUM_LOG_VALUE_FOREGROUND", "{{ foreground }}")
os.setenv("GUM_LOG_VALUE_BACKGROUND", "{{ background }}")
os.setenv("GUM_LOG_SEPARATOR_FOREGROUND", "{{ muted }}")
os.setenv("GUM_LOG_SEPARATOR_BACKGROUND", "{{ background }}")
