{
  "$schema": "https://raw.githubusercontent.com/earendil-works/pi/main/packages/coding-agent/src/modes/interactive/theme/theme-schema.json",
  "name": "dots",
  "appearance": "{{ mode }}",
  "vars": {
    "bg": "{{ background }}",
    "fg": "{{ foreground }}",
    "accent": "{{ accent }}",
    "accent2": "{{ magenta }}",
    "red": "{{ red }}",
    "green": "{{ green }}",
    "yellow": "{{ yellow }}",
    "orange": "{{ orange }}",
    "purple": "{{ magenta }}",
    "cyan": "{{ cyan }}",
    "gray": "{{ muted }}",
    "dimGray": "{{ muted }}",
    "surface": "{{ lighter_background }}",
    "surface2": "{{ selection_background }}",
    "surface3": "{{ selection }}",
    "toolPendingBg": "{{ lighter_background }}",
    "toolSuccessBg": "{{ lighter_background }}",
    "toolErrorBg": "{{ lighter_background }}",
    "customMsgBg": "{{ lighter_background }}"
  },
  "colors": {
    "accent": "accent",
    "border": "accent",
    "borderAccent": "accent2",
    "borderMuted": "surface3",
    "success": "green",
    "error": "red",
    "warning": "yellow",
    "muted": "gray",
    "dim": "dimGray",
    "text": "fg",
    "thinkingText": "gray",
    "selectedBg": "surface3",
    "userMessageBg": "surface",
    "userMessageText": "fg",
    "customMessageBg": "customMsgBg",
    "customMessageText": "fg",
    "customMessageLabel": "accent2",
    "toolPendingBg": "toolPendingBg",
    "toolSuccessBg": "toolSuccessBg",
    "toolErrorBg": "toolErrorBg",
    "toolTitle": "accent2",
    "toolOutput": "gray",
    "mdHeading": "yellow",
    "mdLink": "accent2",
    "mdLinkUrl": "dimGray",
    "mdCode": "orange",
    "mdCodeBlock": "green",
    "mdCodeBlockBorder": "surface3",
    "mdQuote": "gray",
    "mdQuoteBorder": "purple",
    "mdHr": "surface3",
    "mdListBullet": "accent",
    "toolDiffAdded": "green",
    "toolDiffRemoved": "red",
    "toolDiffContext": "gray",
    "syntaxComment": "dimGray",
    "syntaxKeyword": "purple",
    "syntaxFunction": "accent2",
    "syntaxVariable": "fg",
    "syntaxString": "green",
    "syntaxNumber": "orange",
    "syntaxType": "yellow",
    "syntaxOperator": "accent",
    "syntaxPunctuation": "gray",
    "thinkingOff": "surface3",
    "thinkingMinimal": "dimGray",
    "thinkingLow": "accent",
    "thinkingMedium": "accent2",
    "thinkingHigh": "purple",
    "thinkingXhigh": "red",
    "bashMode": "green"
  },
  "export": {
    "pageBg": "{{ background }}",
    "cardBg": "{{ lighter_background }}",
    "infoBg": "{{ selection_background }}"
  }
}
