set -g status-style "bg=default,fg={{ foreground }}"
set -g status-left "#[fg={{ background }},bg={{ accent }},bold] #S #[bg=default] "
set -g status-right "#[fg=blue]#{?pane_in_mode,COPY ,}#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=brightblack]#h "
set -g window-status-format "#[fg={{ muted }}] #I:#W "
set -g window-status-current-format "#[fg={{ accent }},bold] #I:#W "
set -g pane-border-style "fg={{ muted }}"
set -g pane-active-border-style "fg={{ accent }}"
set -g message-style "bg=default,fg={{ foreground }}"
set -g mode-style "bg={{ selection }},fg={{ foreground }}"
set -g message-command-style "bg=default,fg={{ accent }}"
setw -g clock-mode-colour "{{ muted }}"
