# Dream
# Scheme by 5nik7
background #151B30
foreground #D6E4FF
selection_background #D6E4FF
selection_foreground #151B30
url_color #535e7c
cursor #D6E4FF
active_border_color #434E73
inactive_border_color #1b2138
active_tab_background #151B30
active_tab_foreground #D6E4FF
inactive_tab_background #1b2138
inactive_tab_foreground #535e7c

# normal
color0 #1b2138
color1 #FD5A96
color2 #4FFFCD
color3 #FFB894
color4 #7DA6FF
color5 #D69AFF
color6 #4DEAFF
color7 #CCD5FF

# bright
color8 #2E354F
color9 #FD5A96
color10 #4FFFCD
color11 #FFE1A6
color12 #7DA6FF
color13 #D69AFF
color14 #4DEAFF
color15 #A1ADE6
