#!/usr/bin/env python3
"""Regenerate standalone adapters and the manual; --check performs no writes."""
import argparse
from pathlib import Path
import re
import sys
import textwrap

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / 'lib/dots/anodize'))
from cli import parser


def roff(value):
    return str(value).replace('\\', r'\e').replace('-', r'\-').replace('"', r'\(dq')


def manual():
    lines = [r'.\" Generated by tools/generate_anodize_integration.py; do not edit.',
             '.TH ANODIZE 1 "2026-09-25" "Dots" "User Commands"',
             '.SH NAME', 'anodize \\- author palettes and recoverable Dots themes',
             '.SH SYNOPSIS', '.B anodize', '[presentation-options] COMMAND [options]',
             '.br', '.B dots anodize', 'COMMAND [options]',
             '.SH DESCRIPTION',
             'Create and edit palettes from local images, seed colors, existing Dots themes,',
             'or imported palette files. Saves use recoverable file transactions.',
             'Saving does not activate a theme; use the apply command separately.',
             '.PP',
             'Mutating commands prompt on interactive input. Without a terminal or with',
             r'\fB\-\-json\fR, omission of \fB\-\-yes\fR returns a preview.',
             r'\fB\-\-dry\-run\fR always takes precedence over \fB\-\-yes\fR.',
             'Read-only operations create no persistent state.',
             '.SH PRESENTATION OPTIONS',
             'These options precede COMMAND and use the equals form.',
             '.TP', r'.B \-\-color=auto|always|never',
             'Control human-output colors. Auto requires a terminal, a non-dumb TERM,',
             'and no nonempty NO_COLOR. Always overrides NO_COLOR.',
             r'After create, \fB\-\-color HEX\fR instead specifies a seed color.',
             '.TP', r'.B \-\-icons=auto|always|never', 'Control icons where supported.',
             '.TP', r'.B \-h, \-\-help', 'Show help without needing the engine.',
             '.SH COMMANDS']
    actions = next(a for a in parser()._actions if isinstance(a, argparse._SubParsersAction))
    for name, command in actions.choices.items():
        positionals = [a for a in command._actions if not a.option_strings]
        synopsis = 'anodize ' + name + ''.join(' ' + a.dest.upper() for a in positionals) + ' [OPTIONS]'
        lines += ['.SS "' + roff(synopsis) + '"', roff(command.description) + '.']
        for action in command._actions:
            label = ', '.join(action.option_strings) if action.option_strings else action.dest.upper()
            if action.option_strings and action.nargs != 0:
                label += ' ' + (action.metavar or action.dest.upper())
            help_text = action.help or ''
            if action.required:
                help_text += ' (required)'
            if action.choices:
                help_text += ': ' + ', '.join(action.choices)
            lines += ['.TP', '.B "' + roff(label) + '"', roff(help_text) + '.']
    lines += ['.SH INPUTS AND EDITING',
              r'Create requires exactly one of \fB\-\-image FILE\fR, \fB\-\-color HEX\fR,',
              r'or \fB\-\-from THEME\fR. Quote hex values, for example \(aq#725ac1\(aq.',
              'IDs start with a lowercase letter and contain lowercase letters, digits,',
              'underscores or hyphens. Existing theme IDs are never overwritten by create.',
              '.PP',
              'PNG, JPEG and GIF inputs are limited to 32 MiB and 20 million pixels.',
              'Extraction defaults to normal/dark. Run anodize modes for all 23 modes.',
              'Light and dark flags are mutually exclusive.',
              '.PP',
              'Adjustments are absolute values applied to the saved baseline. Repeating',
              'an edit does not compound it. Vibrance, saturation, contrast, brightness,',
              'shadows, highlights, temperature, tint, blackPoint and whitePoint accept',
              r'\-100 through 100. hueShift accepts \-360 through 360. gamma accepts',
              '0.1 through 10. Names are case-sensitive; defaults are zero except gamma (1).',
              '.PP',
              'Color overrides use named keys and six-digit hex values. Derived color0',
              'through color15 aliases cannot be overridden. Resetting adjustments retains',
              'overrides. Re-extraction requires a saved wallpaper or seed.',
              '.SH IMPORT AND EXPORT',
              'Import accepts Anodize JSON, Aether JSON, Base16 flat JSON/simple YAML,',
              'or Dots colors.toml. Aether colors are already adjusted: source adjustments',
              'are retained as provenance, not applied again. Desktop settings and effects',
              'are not imported. Base16 requires every base00 through base0F entry.',
              '.PP',
              'Exports emit raw stdout unless an output file is requested. Output files',
              'use a recoverable transaction and must not already exist. Dry-run export',
              'requires an output file. Raw exports and app previews never contain ANSI.',
              'JSON cannot be combined with app preview or colors-format export.',
              '.SH SAFETY AND RECOVERY',
              'Theme sources live under DOTS/themes/ID. Edits refuse changed generated',
              'files and unsafe filesystem objects. Wallpaper images are copied by default;',
              'reference-wallpaper keeps an external absolute dependency. Exports are not',
              'self-contained wallpaper archives.',
              '.PP',
              'A saved transaction includes a recovery identifier. Inspect it with',
              r'\fBdots files history\fR and undo with \fBdots files undo ID\fR.',
              'Undo refuses destructive restoration after drift.',
              '.PP',
              'Apply uses the existing Dots publisher and app connectors. The optional',
              'background flag preflights session support and wallpaper availability.',
              'Wallpaper activation runs after publication; if it fails, the app theme',
              'remains published and the command reports failure. GIF wallpapers cannot',
              'be activated. Native Windows authoring, Android APK and TUI are deferred.',
              '.SH SHELL COMPLETION',
              'Bash, Zsh and Fish adapters are emitted as plain shell source, without the',
              'Go engine. Loading them performs no discovery. Tab completion reads static',
              'command metadata and available theme names; it never executes leaf commands.',
              '.PP', '.nf',
              'source <(anodize completion bash)',
              'autoload -Uz compinit; compinit',
              'source <(anodize completion zsh)',
              'anodize completion fish | source', '.fi',
              '.PP', 'The Zsh lines assume compinit has not already run in the current shell.',
              'Repository shell completion trees also include the standalone adapters.',
              '.SH ENVIRONMENT',
              '.TP', '.B DOTS', 'Theme repository root; defaults to the executable checkout.',
              '.TP', '.B ANODIZE_ENGINE', 'Explicit prebuilt private engine executable.',
              '.TP', '.B DOTS_COLOR, DOTS_ICONS', 'Default presentation modes: auto, always or never.',
              '.TP', '.B NO_COLOR, TERM', 'Control automatic color selection.',
              '.TP', '.B COLUMNS', 'Human-output wrapping width.',
              '.TP', '.B HOME, XDG_CONFIG_HOME, XDG_STATE_HOME',
              'User config, theme and recovery-state roots used by Dots.',
              '.SH FILES',
              '.TP', '.B themes/ID/anodize.json', 'Saved baseline, adjustments, overrides and generated-file receipts.',
              '.TP', '.B themes/ID/colors.toml, themes/ID/theme.toml', 'Generated Dots theme files.',
              '.TP', '.B themes/ID/backgrounds/', 'Copied wallpaper images.',
              '.SH EXAMPLES', '.nf',
              roff("anodize create dusk --color '#725ac1' --dry-run"),
              roff("anodize create dusk --color '#725ac1' --yes"),
              'anodize preview dusk',
              roff('anodize edit dusk --adjust saturation=12 --dry-run'),
              roff('anodize apply dusk --dry-run'),
              roff('anodize apply dusk --yes'), '.fi',
              '.SH EXIT STATUS',
              '0: success or preview. 1: validation or operational failure. 2: argument usage error.',
              '.SH DEPENDENCIES',
              'Bash 4.4 or newer, Python 3.11 or newer and existing POSIX Dots theme tools.',
              'Build the private engine explicitly from the checkout using',
              r'\fBpython3 \-B tools/verify_anodize.py build\fR (installed Go 1.27.1).',
              'Help, completion generation and completion queries need no Go engine.',
              'There are no automatic builds or downloads.',
              '.SH SEE ALSO', '.BR bash (1),', '.BR zsh (1),', '.BR fish (1)',
              '.PP', 'The Dots checkout documentation: docs/anodize.md and docs/files.md.']
    return '\n'.join(line if line.startswith('.') else textwrap.fill(line, 78, break_on_hyphens=False)
                     for line in lines) + '\n'


def artifacts():
    for shell in ('bash', 'zsh', 'fish'):
        source = (REPO/'lib/dots/completion'/shell).read_text()
        source = re.sub(r'\bdots\b', 'anodize', source).replace('_dots', '_anodize').replace('DOTS_BASH', 'ANODIZE_BASH')
        yield REPO/'lib/dots/anodize/completion'/shell, source
    yield REPO/'man/anodize.1', manual()


if __name__ == '__main__':
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    stale = []
    for path, content in artifacts():
        if args.check:
            if not path.is_file() or path.read_text() != content:
                stale.append(str(path.relative_to(REPO)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        sys.exit('Stale Anodize artifacts: ' + ', '.join(stale))
