background = "#f2ecbc"
foreground = "#545464"
muted = "#8a8980"
accent = "#624c83"
selection = "#c9cbd1"
error = "#e82424"
warning = "#e98a00"
info = "#5a7785"
hint = "#5e857a"
mode = "light"
red = "#e82424"
green = "#5e857a"
yellow = "#e98a00"
blue = "#5a7785"
magenta = "#624c83"
cyan = "#5a7785"
bright_red = "#e82424"
bright_green = "#5e857a"
bright_yellow = "#e98a00"
bright_blue = "#5a7785"
bright_magenta = "#624c83"
bright_cyan = "#5a7785"
bright_foreground = "#545464"
dark_foreground = "#8a8980"
light_foreground = "#545464"
dark_background = "#f2ecbc"
darker_background = "#f2ecbc"
lighter_background = "#c9cbd1"
orange = "#e98a00"
brown = "#8a8980"
