background = "#222436"
foreground = "#c8d3f5"
muted = "#636da6"
accent = "#c099ff"
selection = "#2d3f76"
error = "#c53b53"
warning = "#ffc777"
info = "#0db9d7"
hint = "#4fd6be"
mode = "dark"
red = "#ff757f"
green = "#c3e88d"
yellow = "#ffc777"
blue = "#82aaff"
magenta = "#c099ff"
cyan = "#4fd6be"
bright_red = "#ff757f"
bright_green = "#c3e88d"
bright_yellow = "#ffc777"
bright_blue = "#82aaff"
bright_magenta = "#c099ff"
bright_cyan = "#4fd6be"
bright_foreground = "#c8d3f5"
dark_foreground = "#636da6"
light_foreground = "#c8d3f5"
dark_background = "#222436"
darker_background = "#222436"
lighter_background = "#2d3f76"
orange = "#ffc777"
brown = "#636da6"
