# xinitrc

setxkbmap -option caps:escape & # remap CAPS to ESC
xrdb "$HOME/.config/x11/Xresources" # Load X11 settings and colors
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh &
# sleep 1 && eww open-many bar0 bar1 > /dev/null 2> /dev/null & # Launch eww  # TODO: Fix this
xsetroot -cursor_name left_ptr &  # Set cursor for the background
#picom --experimental-backends -b 2> /dev/null & # Compositor
flashfocus 2> /dev/null & # Focus indicator

sxhkd & # Keybindings
exec bspwm

# vim:ft=sh