# shellcheck disable=SC2148

# generated by Git for Windows
# shellcheck disable=SC1090
test -f ~/.profile && . ~/.profile
# shellcheck disable=SC1090
test -f ~/.bashrc && . ~/.bashrc

[ -z ${WSLENV+x} ] || export PATH="${PATH:+"$PATH:"}$HOME/bin/win-bash-xclip-xsel"
